### ISSUE TITLE
How to incrementally deploy typescript bot from VS Code?

### ISSUE THREAD

**Issue by bbojilov** [Microsoft/BotBuilder-Samples#1053]
Hi, 

I cloned and deployed 13.basic-bot using Bot Cli. Now I did minor changes in typescript files and want to deploy it to Azure App Service. How to do that? I don't want to clone the whole bot again just web app source code? 
If I user aspnet core and Visual Studio I test to download publishing profile and successfully deploy the back-end using Visual Studio. How to do that with Typescript and VS Code?

Best,
Bojil

**Comment by tdurnford** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.

**Comment by deniercounter** [comment]
Yep .. that is annoying for Node developer.

I ended up with having two projects. One coming from the via the Azure portal generated source in JavaScript and another one, where I actually really develop in TypeScript. 

In order to deploy I have to copy and paste the JavaScript files into my local Azure project and deploy from there via the az cli.

This is not elegant at all, but there is no automatic Azure way to deploy TypeScript.
