### ISSUE TITLE
V4 VSIX - Cannot save project

### ISSUE THREAD

**Issue by mgazell** [Microsoft/BotBuilder-Samples#1086]
Using the V4 VSIX template, I created a new project. However, I get an error message when I try to save the project. The issue is present for both EchoBot and EmptyBot projects. The message that I get is "The operation could not be completed. No such interface supported."

## To Reproduce
1. Go to 'Visual Studio - File - New Project'
2. Click on 'BotFramework on the left and select 'EchoBot' from the right. Click on OK
3. Click on Save Project. Specify a local location and click on 'Save'
4. An error message is shown. Please see screenshot.

Issue seems to be only with this template and all other templates work.
![image](https://user-images.githubusercontent.com/44647263/49966057-02a6f300-feed-11e8-9bda-43c046ecde96.png)

**Comment by CoHealer** [comment]
Assigning @Zerryth to assist

**Comment by Zerryth** [comment]
@mgazell I wasn't able to repro the error you're getting.
___

**Repro**:
I had uninstalled the v4 template (Tools > Extensions and Updates... > Found Bot Builder V4 SDK Template > Uninstall), then installed it once again to make sure I had the most up-to-date published (Version: 4.2.0)

Ctrl + Shift + N (new project) > EchoBot1 > Ok
and
Ctrl + Shift + N (new project) > EmptyBot1 > Ok

F5 to run both. Both bots worked as intended in BF Emulator.
___
* I imagine you actually do have the up-to-date VSIX version installed since you actually have the EmptyBot template, however does the issue persist if you uninstall and reinstall the template?

* Also, you mention "other templates" work--which templates are you running that work? The 4.2 v4 VSIX only have Empty and Echo bot templates, but I'm curious to know what other template did work for you

**Comment by mgazell** [comment]
Hi @Zerryth 

I tried uninstalling and installing again with no success. I wanted to mention that I am using the community edition of VS 2017. I also dont get an option to save the project when I initially create the project (see screenhot below). 

![capture](https://user-images.githubusercontent.com/44647263/50566813-e20fd300-0d0b-11e9-9765-06b11bb258e8.PNG)

When I said other templates work, I meant other project types like a .net core app or a winforms app.

**Comment by Zerryth** [comment]
Hmm just installed VS Community 2017 as well, and again things seem to be working as intended and can't get a repro of your issue.

Although I do note that when I go to create a project, it does let me choose where to save project as well

![image](https://user-images.githubusercontent.com/35248895/50567968-55134c80-0d00-11e9-8bbb-5828220fa5eb.png)

![image](https://user-images.githubusercontent.com/35248895/50567977-7e33dd00-0d00-11e9-9361-a2791f695507.png)

Are you using an up-to-date version of VS Community?

**Comment by Zerryth** [comment]
Alrighty @mgazell so I actually went into Azure, created a virtual machine with only Visual Studio Community 2017 to have a _completely clean slate_, and was able to successfully download the VSIX and create/save a project from the template. It also let me create and save the project in one go.

Doing an internet search, it doesn't appear to be a Bot Framework-specific issue, but rather something happening on the Visual Studio 2017 side of things.

These two posts ([post 1](http://vsx-insider.blogspot.com/2008/02/new-custom-project-can-be-saved.html), [post 2](https://www.devexpress.com/Support/Center/Question/Details/T600201/the-operation-could-not-be-completed-no-such-interface-supported-error-occurs-on-an)) mention the solution that worked for them was enabling "Save new projects when created". 

I'd suggest trying the workaround in post 1.

**Comment by mgazell** [comment]
Hi @Zerryth ,

The workaround worked. After I enabled "Save new projects when created", I was prompted to save the project in the new project dialog itself. The solution built fine after that. As part of my internet search I did see posts indicating that part of the problem was because the project was not being saved initially. But, I was not aware that there was a setting to force this. Thanks for your help on this.
