### ISSUE TITLE
Web Chat channel not showing the Suggested actions upon bot start

### ISSUE THREAD

**Issue by GamalMohamed** [Microsoft/BotBuilder-Samples#1125]
I'm trying to run the "SuggestedActionsBot" sample, it works normally on the Emulator, but when I deploy it and try to test it in the Web Chat channel in azure portal, it doesn't show the Suggested action upon Bot start and needs me to type anything and send it in order to actually start the conversation!

**Comment by jwiley84** [comment]
Hi @GamalMohamed! 

This has to do with the way that particular sample is structured.  The SuggestedActionsBot (both C# and Node) will only send the prompts ("What color is best?") after either A) a message is received from the user or B) a ConversationUpdate activity that a user has joined has been received (at which point, the welcome message is sent, then the prompt). Because the 'Test in WebChat' on the Azure portal sends the conversationUpdate activity only when the user has send first message is sent, the latter option (B) is never hit, and so the bot waits for a message from the user instead.  

https://github.com/Microsoft/BotFramework-WebChat/issues/869

I'm going to close this, because this is a known and tracked issue already.
