### ISSUE TITLE
Error reading bot file

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1190]
## Sample information
1. Sample language: nodejs  
2. Sample name: 50.diceroller-skill

## Describe the bug

node ./index.js  Error reading bot file. Please ensure you have valid botFilePath and botFileSecret set for your environment.
                { Error: ENOENT: no such file or directory, stat
                'C:\Users\botbuilder-samples\samples\javascript_nodejs\50.diceroller- 
                 skill\cortana- skill.bot'}

## To Reproduce
1. Determine the node version which should be above 8.5
2. Run npm install command.
3.Run npm start command. An error occurs here,
     -	node ./index.js  Error reading bot file. Please ensure you have valid botFilePath and botFileSecret set for your environment.
                { Error: ENOENT: no such file or directory, stat
                'C:\Users\TejaswiniNandakumar\botbuilder-samples\samples\javascript_nodejs\50.diceroller- 
                 skill\cortana- skill.bot'}
We wont get botFileSecret yet, so how to use it here?

## Expected behaviour
The sample should work according the readme.

**Comment by mdrichardson** [comment]
The issue is this line:

`const BOT_FILE = path.join(__dirname, (process.env.botFilePath || '/cortana-skill.bot'));`

needs to be:

`const BOT_FILE = path.join(__dirname, (process.env.botFilePath || '/diceroller-skill.bot'));`

I'll roll this into my other PR of small fixes.

**Comment by sgellock** [comment]
We should test this change on a non-Windows os.  I think the OS portable approach may be:


const BOT_FILE = path.join(__dirname, (process.env.botFilePath || 'diceroller-skill.bot'));


But I’m not 100 certain

On Jan 30, 2019, at 2:08 PM, Michael Richardson <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is this line:

const BOT_FILE = path.join(__dirname, (process.env.botFilePath || '/cortana-skill.bot'));

needs to be:

const BOT_FILE = path.join(__dirname, (process.env.botFilePath || '/diceroller-skill.bot'));

I'll roll this into my other PR of small fixes.

**Comment by mdrichardson** [comment]
@sgellock 

Good call. The other samples have:

`const BOT_FILE = path.join(__dirname, (process.env.botFilePath || ''));`

so I've adjusted the PR to reflect that to keep it in line. This sample was also missing a `.env` file, so I included that as well, with `botFilePath=diceroller-skill.bot`
