### ISSUE TITLE
[V3] Update bootstrap to version "3.4.1" in  CSharp/Blog-LUISActionBinding/LuisActions.Samples.Web

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#1300]
V3 issue

CSharp/Blog-LUISActionBinding/LuisActions.Samples.Web/packages.config needs to be updated to use the following version of bootstrap:

<package id="bootstrap" version="3.4.1" />

[bug]

**Comment by EricDahlvang** [comment]
Created a PR for this.  However, we should consider removing this sample from this repository entirely since it is also maintained here now: https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/CSharp/Samples/LuisActions and the node version here: https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/LuisActionBinding

**Comment by sgellock** [comment]
@EricDahlvang RE:  removing it.  Yes.  Please do that instead.

**Comment by EricDahlvang** [comment]
Closing (PR removing the V3 Action Binding samples has been merged)
