### ISSUE TITLE
User state not maintained for new users

### ISSUE THREAD

**Issue by iammelvin** [Microsoft/BotBuilder-Samples#1311]
## Sample information
1. Sample type: Basic Bot
2. Sample language: nodejs
3. Sample name: custom state

## Describe the bug
I have created a new basic bot project using azure bot service in azure portal and I have downloaded the code to work locally.I use azure blob storage to handle user/conversation state.I am using directline api to connect to web app bot from my ionic app. When I convert that to apk and making calls from multiple devices at the same time results in data mix up. The basic bot project has a greeting dialog and the user who types their name first gets saved in the user state and that same response is returned to the other user too. How to solve this issue ? I am using ngrok while running the bot project locally in my machine and updated the endpoint in azure with my ngrok url instead of the web app url of the bot.

## Expected behavior
Reset conversation for all new users/requests

## Additional context

[bug]

**Comment by v-kydela** [comment]
Hello @iammelvin 

My first guess is that your bot isn't recognizing these users as different users and is therefore using the same user state for both of them. Remember that user state depends on a user ID retrieved from an activity object.

To help diagnose this problem, please include the following code in your `onTurn` handler and see if the users are indeed seen as distinct:

```node
await turnContext.sendActivity(`User ID: ${turnContext.activity.from.id}`);
```

**Comment by iammelvin** [comment]
@v-kydela the basic bot onturn method has a greeting dialog and that dialog returns the below user data

```
await step.context.sendActivity(`Hi ${userProfile.name}, from ${userProfile.city}, nice to meet you!`);
await step.context.sendActivity(`You can always say 'My name is <your name> to reintroduce yourself to me.`);
```

so you saying that I should add the user Id from activity context in this response ?

**Comment by v-kydela** [comment]
@iammelvin - You should send the user ID to the user for the sake of diagnostics, though it doesn't matter where. You can alternatively just check the value while debugging.

I notice in your screenshots that the user is labeled "Demo" in both cases, and that does suggest that the user ID is the same.

**Comment by iammelvin** [comment]
@v-kydela Thanks I changed that Id as something unique now in my blob storage I have different blobs for each users. But is there something I need to manage in my code by checking the user Id each time against the blob storage values of that user or bot framework does that ?

**Comment by v-kydela** [comment]
@iammelvin - The Bot Framework does automatically use the user ID from the turn context's activity to access user state. For that to happen, it also automatically populates incoming activities with an appropriate user ID. But since you're using your own Direct Line client, I think you have a lot of control over how that happens and so it's difficult to answer your question completely without seeing your source. How are you accessing user state?

In any case, I recommend just testing your bot and seeing what happens.

**Comment by iammelvin** [comment]
@v-kydela Ok I have unique user id for each user and each user state is saved separately in blob storage but as per your previous post the bot framework handles user state but I still get data mixed up between users.I haven't added any extra code I am working with the basic bot created using azure services.The only thing I have done is added blob storage.

**Comment by v-kydela** [comment]
@iammelvin - From your screenshots, it doesn't look like data is getting mixed up between users. What it looks like is that in some cases it interprets a user's name as both a name and a city. Is that correct?

My guess is that the Basic Bot's `UpdateGreetingState` method is updating the user's city because your LUIS app thinks "Vivek" is a city name. There are a few ways you can test this theory. You can use the testing panel in luis.ai and enter "Vivek" and see if it recognizes that as a `userLocation` entity. You can also set breakpoints in your bot code when you're testing locally to see if that's where the location is getting updated:

![image](https://user-images.githubusercontent.com/41968495/54650544-3f463580-4a6c-11e9-9962-12b8e9033972.png)

**Comment by v-kydela** [comment]
@iammelvin - Are you still working on this?

**Comment by iammelvin** [comment]
@v-kydela Hi sorry for the late response and thanks for the help.The issue was with the userprofile update  method which uses LUIS to return entity and update the user name and city.

Btw it would be great to see an example in which I can switch from the active dialog to other dialog when the user interrupts.Any idea how to do that ?

**Comment by v-kydela** [comment]
@iammelvin - Let me see if I understand. You want the same functionality of being able to update the greeting state, but instead of updating it as an additional action on the same turn that current dialog is processed, you want the state to be updated in its own dialog and handle that on its own turn. In addition to that, you want a prompt to check if the user wants to continue an interruption once the interruption has occurred. Is that correct?

**Comment by iammelvin** [comment]
@v-kydela Leave that first part just help me with the second and yes want to prompt if user interrupts and want to switch dialogs based on new luis result.

**Comment by v-kydela** [comment]
@iammelvin - Prompting on interrupt is a simple matter of adding a new dialog with a `ConfirmPrompt` to the top of the stack and then popping it off the stack when the user says no.

However, I want to advise against this because I think most people would consider this a bad user experience. Whether or not the user wants to interrupt, you're making the user take an extra step before doing what they want to do. My recommendation is to just send a message explaining that an interruption has occurred and the user can go back to the original dialog by entering a keyword, and then continue with the interrupting dialog on the same turn.

**Comment by iammelvin** [comment]
@v-kydela  It would be great if you include an example for user interruption based on the new LUIS intent when there is an active dialog.

**Comment by v-kydela** [comment]
@iammelvin - I suppose we could use an interruption sample, but in the meantime you can have a look at how interruptions are handled in the [Enterprise Template](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/enterprise-bot/src/dialogs/shared/enterpriseDialog.ts).
