### ISSUE TITLE
[ARM Bugbash] az ad app create is creating a different kind of app

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotBuilder-Samples#1366]
## Describe the bug
I used `az ad app create --display-name "ArmBugBash" --password "testpassword123!" --available-to-other-tenants` to create an app, then went to https://apps.dev.microsoft.com/ ... but it does not show up. When I create a bot from the azure portal, those apps show in apps.dev.microsoft.com. 

Apparently this app is different.?

Clicking 'manage' in the Bot Channel Registration settings does take me to the app.  I see it has an empty Web API Platform:

![image](https://user-images.githubusercontent.com/11055362/55266307-8fc24d80-5239-11e9-8446-5964bce6a922.png)

**Comment by stevengum** [comment]
@EricDahlvang 

After digging into this a little, this is because the signInAudience for an app created through the above command has a different `"signInAudience"` value. In the preview page, the listed Supported account types is the "Multiple organizations" which indicates that it supports AD and not MSA for authentication.

![multipleorganizations](https://user-images.githubusercontent.com/14935595/55419717-41a79580-552a-11e9-97ee-1f4f6007e83b.jpg)

Clicking on "Multiple organizations" leads you to the Authentication page (accesible through the left-side menu under the **Manage** section:

![Manage-Authentication-Supported account types](https://user-images.githubusercontent.com/14935595/55419778-5f74fa80-552a-11e9-9dde-65ba3ec5d1b4.jpg)

Note the bottom section indicates that the app doesn't support personal accounts, and that the only way to change this setting is through the manifest itself. The Manifest page is also under the **Manage** section.

Near the bottom of the manifest is the key we're looking for, `"signInAudience"`:

![bottom-half-manifest](https://user-images.githubusercontent.com/14935595/55419938-b67acf80-552a-11e9-8bb2-8737062e04fb.jpg)

Change its value to `"AzureADandPersonalMicrosoftAccount"` like so:

![below-manifest-after](https://user-images.githubusercontent.com/14935595/55419968-c72b4580-552a-11e9-9aa7-10d80509f5ff.JPG)

Hit the save button which is at the top of the rendered manifest. This will change your app so that non-AD accounts can sign in, making it a Converged App.

Here's the list of Converged Apps at https://apps.dev.microsoft.com/#/appList _before_ saving the changes in the manifest:

![list-of-apps-before](https://user-images.githubusercontent.com/14935595/55420140-2be6a000-552b-11e9-9044-d1c7b03c93e3.PNG)

And here's the app showing up in the list after the manifest changes were saved and propagated through the system:

![list-of-apps-after](https://user-images.githubusercontent.com/14935595/55420194-47ea4180-552b-11e9-839e-119d5996d0d6.JPG)

___

I'm planning on [adding signInAudience argument](https://github.com/Azure/azure-cli/issues/8820) support to the `az ad app create` command, but the problem is that we're blocked by an [out of date swagger file](https://github.com/Azure/azure-rest-api-specs/issues/5427).
