### ISSUE TITLE
Increment Generator versions as part of automated build

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder-Samples#1394]
In the generators for

File: 
https://github.com/Microsoft/BotBuilder-Samples/blob/master/generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json

Line 13 and line 27 need to have the versions stamped as part of the build. 

https://github.com/Microsoft/BotBuilder-Samples/blob/master/generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec

Line 5. 

Versions should match, and should match the semver of the overall build. 

This should apply to all 3 of the CoreBot, EchoBot, EmptyBot.

**Comment by BruceHaley** [comment]
New build "BotBuilder-Samples-DotNet" https://fuselabs.visualstudio.com/SDK_v4/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=398
replaces the 3 separate builds, giving them all the same build number, and stamping versions in .json files. It has CI, PR, and scheduled triggers. NuGet push remains part of this build rather than being in a separate Release pipeline.
