### ISSUE TITLE
Docs on the timex results from LUIS are sparse

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotBuilder-Samples#1471]
The datetimev2 / timex extractor feature of LUIS is super cool and powerful and works really well.

However, the docs on how to use timex are very minimal, and currently point to a very academic PDF document.

It would be great if we could provide examples of using the timex to do normal things like creating a single or repeating calendar schedule type date from the timex.

A simple breakdown of the various formats used by Timex and what they mean would also be very welcome!

Current docs:
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-datetimev2

Timex explanation:
http://www.timeml.org/tempeval2/tempeval2-trial/guidelines/timex3guidelines-072009.pdf

**Comment by sgellock** [comment]
@Kaiqb can you drive please?  thanks.

**Comment by garypretty** [comment]
@johnataylor I think expanding your sample readme to cover common scenarios (as @benbrown described above), as you suggested, probably makes sense.  

I think it might also be a good idea to add a reference to the TIMEX sample somewhere in our docs, so that folks who are using LUIS can be pointed to the sample.

@JonathanFingold could you suggest an appropriate place within our docs where such a call out could be made?

**Comment by JonathanFingold** [comment]
As a stand-alone topic, I might put it under resources, or add a shout out in new recognizers concept article, with a short reference topic that covers the bits and pieces. Currently, we have a very brief discussion hidden here: https://docs.microsoft.com/azure/bot-service/bot-builder-primitive-prompts#parse-and-validate-input.
