### ISSUE TITLE
[Question] Unable to add more than 3 buttons in ThumbnailCard

### ISSUE THREAD

**Issue by Sachin-Intap** [Microsoft/BotBuilder-Samples#149]
I am trying to create ThumbnailCard with 4 buttons (CardAction imBack). According to the documentation, both the Thumbnail and HeroCard have a limit of 5 buttons. But the card is not showing more than 3 buttons. Also i am unable to show complete text in card itself (around 100-200 characters).

Thanks 
Sachin

**Comment by JasonSowers** [comment]
What SDK are you using node/.NET, and what channel(s)?

**Comment by Sachin-Intap** [comment]
i am using Node and Testing on Skype.

**Comment by nwhitmont** [comment]
@Sachin-Intap According to the Skype documentation at https://dev.skype.com/bots - under section 6 "Cards and actions > CardActions > Hints and tips" it describes the limitations of the number of buttons that can be displayed depending on the other content included in the card.

The reason is because you can only use three buttons when including the other content like image, title, subtitle, text, etc.

**Hints and tips**
>Cards can include up to 6 buttons, depending on how many other text and media elements are included:
- Image, title, subtitle, text – 3 buttons
- Title, subtitle, text – 5 buttons
- Text or image only – 6 buttons

**Comment by Sachin-Intap** [comment]
Thanks
 "Title, subtitle, text – 5 buttons" will work here. But i am still unable to show complete text in card.
![screen shot 2017-07-06 at 12 11 12 pm](https://user-images.githubusercontent.com/7310730/27898591-46306bca-6244-11e7-9c12-9a5ad366cc97.png)
