### ISSUE TITLE
How can we handle nested multiturn 

### ISSUE THREAD

**Issue by ArunaJapannavar** [microsoft/BotBuilder-Samples#1584]
#Can you please let us know how can we handle mutiturn requests for eg:
Ques) I need more information on some sectors?
 Ans) What sectors are you looking for information in?
   1) HR
   11) IT
  111) Finance

If the user selects any choices like HR it should also populate the answer related to HR from the KB.

**Comment by JonathanFingold** [comment]
Take a look at sample 43.complex-dialog. That might give you enough insight to start trying out similar structures in your own code.

**Comment by jwiley84** [comment]
What @JonathanFingold is correct. You're going to want to look at the complex dialog samples. Specifically, you're going to want to have at least two dialogs, a 'Main' and a 'Sector'. Then, inside the Sector dialog, you're going to want to have a dialog step that checks user responses and routes to the correct QnA KB. This is a VERY rough mockup in C# of what that might look like:

![image](https://user-images.githubusercontent.com/17333688/60117222-7ba1c580-972e-11e9-9324-1067b34bfd1e.png)


The different qnaMakers (HRqnaMaker, ITqnaMaker, and FinanceqnaMaker) would have to be created in your main bot in order to be called here this way. This is also doable in Node, though I'm not as proficient with that.
