### ISSUE TITLE
 javascript_es6/01.browser-echo sample throws an error in Edge

### ISSUE THREAD

**Issue by anushaRaoR** [microsoft/BotBuilder-Samples#1618]
## Sample information
1. Sample language:  es6
2. Sample name: javascript_es6/01.browser-echo

## Describe the bug
The sample '01.browser-echo' works fine on Chrome but throws up an error on Edge.
**Error**: "SCRIPT1028: SCRIPT1028: Expected identifier, string or number
app.js (16292,24)"

The issue is with the use of object spread operator which is not supported in Edge : 
const card = { ...other };

## To Reproduce
1. Run the sample '01.browser-echo' on the Command Prompt.
2. Open Edge and type 'http://localhost:8080' and enter.
3. Page doesn't show anything and is blank.
4. Press F12 to inspect element and you will see the error on the console "SCRIPT1028: SCRIPT1028: Expected identifier, string or number
app.js (16292,24)".

## Additional context
- Tried using  @babel/plugin-transform-spread and then  including  @babel/plugin-transform-spread and @babel/plugin-proposal-object-rest-spread in the presets in .babelrc file, but it still shows the same error.
 - The targets for the presets in .babelrc file only specifies for the Chrome version but not for Edge.

[bug]

**Comment by compulim** [comment]
```js
const card = { ...other };
```

It could become

```js
const card = Object.assign({}, other);
```

**Comment by compulim** [comment]
It also throws in IE11. I am fixing it.

**Comment by compulim** [comment]
@anushaRaoR the PR is up.

Although we have the fix for the sample and the sample will work in IE11, there are some issues with Bot Framework SDK need to be addressed before this sample will work. Notably,

- https://github.com/microsoft/botbuilder-js/issues/1073
- https://github.com/microsoft/botbuilder-js/issues/1075
- https://github.com/microsoft/botbuilder-js/issues/1076
