### ISSUE TITLE
Do we have to run dispatch script every time we add a  new intent in Luis / QnA?

### ISSUE THREAD

**Issue by NikhilBansal21** [microsoft/BotBuilder-Samples#1662]
Sample - NLP Dispatch
 Hi,
For the above sample, If we update our agents with some new intents, then do we have to run dispatch scripts again?

**Comment by jwiley84** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.


That being said, the short answer is yes. You'd run 'dispatch refresh', to refresh dispatch and have it map to the new intents in your LUIS or QnA. Otherwise, if you have luis models for "Home Automation", "Calendar" and "Travel", but later added something like a "Recipes and Cooking" model, your dispatch wouldn't route anything to that final model. 

The `dispatch refresh` command is a combination of 'train' and 'publish' and it's sole purpose is handling this exact situation.
