### ISSUE TITLE
suggestedActionsBot.js - Display actions vertically instead of horizontal?

### ISSUE THREAD

**Issue by MaartenBlomer** [microsoft/BotBuilder-Samples#1692]
Currently the suggested answers are listed horizontally, is it possible to list them vertically?

So instead of this: 
![image](https://user-images.githubusercontent.com/53562084/62529583-36010e00-b83f-11e9-8117-e785dd1cd39a.png)

Do this:
![image](https://user-images.githubusercontent.com/53562084/62529694-65177f80-b83f-11e9-934e-93deea2bb8d0.png)

**Comment by tdurnford** [comment]
Unfortunately, each channel is responsible for how they display things like suggested actions to the user, and eventhough Web Chat is highly customizable  in some aspects, it does not allow you to change how suggested actions are rendered. 

If you want the options to stack vertically, I would recommend using a Hero Card instead of Suggested Actions. 

**BotFramework SDK v4 (Node)**
```javascript
const reply = { attachments: [CardFactory.heroCard('', 'What is the best color?', [], ['Red', 'Yellow', 'Blue'])] }
await turnContext.sendActivity(reply);
```

**Screenshot**
![image](https://user-images.githubusercontent.com/17039790/62568554-57afc480-b842-11e9-9ee9-e5cf17a6893a.png)

**Comment by sgellock** [comment]
@CoHealer please be mindful of the customer labels
