### ISSUE TITLE
Proactive message example issue

### ISSUE THREAD

**Issue by jctrebalag** [Microsoft/BotBuilder-Samples#170]
### SDK Platform

Node SDK

### URL of Code Sample

https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages/startNewDialog

### Problem Description

Hi,
I'm trying to use the proactive message example and I'm dealing with an issue regarding the 'resume' option allowed by the patched beginDialog method(cf. botadapter.js).
```
function startProactiveDialog(address) {
  bot.beginDialog(address, "*:/survey", {}, { resume: false });
}
```
Actually, when it is set to 'false', the bot crashes considering 'resume' option as 'undefined'. When set to 'true', it simply won't trigger the proactive message.
Otherwise, when not using botadapter.js and the 'resume' option, proactive message works but stopping the current conversation.

Thanks for your help.

**Comment by mwbrown66** [comment]
Running into this exact behavior.  Did you figure anything out or get a response?

**Comment by billmei** [comment]
The link to that code sample is now giving a 404.

**Comment by benbrown** [comment]
Here is an updated link to the code in question:
https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/core-proactiveMessages/startNewDialog

**Comment by billmei** [comment]
Thanks @benbrown. For anyone else Googling this, here is the GitHub canonical link (permalink) to the code sample, in case it disappears again: https://github.com/Microsoft/BotBuilder-Samples/tree/109b176ea3791687e31f6ab31e7ea06f380a9186/Node/core-proactiveMessages/startNewDialog

**Comment by CoHealer** [comment]
@tdurnford, can you please assist?

**Comment by tdurnford** [comment]
I apologize we didn't get to this issue sooner. 

Looking at the updated source code, it seems the `beginDialog` method behaves differently than it did in previous versions of the v3 SDK. The method currently accepts an `address` and a `dialogId` like it did before; however, it looks like it also accepts `dialogArgs` which get passed along to the dialog and a `done` callback function which are both optional parameters. Using the function call in the issue above now would result in a TypeError since the done `parameter` is expected to be a function and not the behaviors you are describing.

```javascript
    /**
     * Proactively starts a new dialog with the user. Any current conversation between the bot and user will be replaced with a new dialog stack.
     * @param address Address of the user to start a new conversation with. This should be saved during a previous conversation with the user. Any existing conversation or dialog will be immediately terminated.
     * @param dialogId ID of the dialog to begin.
     * @param dialogArgs (Optional) arguments to pass to dialog.
     * @param done (Optional) function to invoke once the operation is completed.
     */
    beginDialog(address: IAddress, dialogId: string, dialogArgs?: any, done?: (err: Error) => void): void;
```

Closing as it appears to be an old issue.
