### ISSUE TITLE
Minor indentation issue - javascript_nodejs/03.welcome-users/bots/welcomeBot.js

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotBuilder-Samples#1714]
## Sample information
1. Sample type: [Incorrect indentation]
2. Sample language: [nodejs]
3. Sample name: <03.welcome-users>

## Describe the bug
We are citing from this [sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/03.welcome-users/bots/welcomeBot.js) in this [article](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&branch=pr-en-us-1671&tabs=javascript). 

The code snippet (javascript_nodejs/03.welcome-users/bots/welcomebot.js?range=65-88) seems not indent correctly. 

## Expected behavior
Format the indentation.

## Screenshots

![image](https://user-images.githubusercontent.com/32497439/63373945-afb7f200-c33d-11e9-9170-0a5f54617ce2.png)

## Additional context
If the lines of this snippet will be changed, please let us know. 

[bug]

**Comment by Zerryth** [comment]
Hmm, took a look at the `.onMembersAdded()` method that you have in question, and its indentation looks fine to me.
____
Perhaps you're referencing the indentation going on in LN 76 - 79, the 2nd message sent?

* It's sending a longer block of text in its message, hence the string concatenation :heavy_check_mark:
   * Best done this way, instead of 1 long string, to not have 1 line that's excessively long with extreme horizontal scrolling w/o wrap
   * For example, to compare, in our Python SDK's linting rules, it specifies that 1 line can have a max of 120 characters ([max-line-length=120](https://github.com/microsoft/botbuilder-python/blob/master/.pylintrc#L343))
  *   LNs 77 - 79 are also properly indented in this string concatenation, to show that it's a continuation of LN 76
 * As for the indentation sizes themselves, if you compare the [eslint rules set in the botbuilder-js repo](https://github.com/microsoft/botbuilder-js/blob/master/.eslintrc.json#L25), it specifies that indentation should be 4 spaces :heavy_check_mark:
    * `.onMembersAdded()`'s indentation all follow 4-space indentation rule
___
Resolving issue as indentation looks good in sample

**Comment by zxyanliu** [comment]
Thank you! @Zerryth
