### ISSUE TITLE
Prompted to copy/paste a code once the Login button is clicked on the Authentication Prompt

### ISSUE THREAD

**Issue by Talhakh** [microsoft/BotBuilder-Samples#1785]
## Description
Expected behavior is that once the user clicks on "Login" button he will be authenticated and the waterfall model will continue on to the next step. However, user gets prompted to copy/paste a code in the chat window to continue

## To Reproduce
1. Clone the bot samples; 24 bot authentication 
2. Type anything
3. Click on Login
4. Authenticate & user will be prompted to copy paste a token

## Expected behavior
Continue on to the next waterfall step without being prompted to copy/paste the token.

## Screenshots
![image](https://user-images.githubusercontent.com/13640546/65848976-cb2a0a00-e38b-11e9-9bb2-9ce2e1477ce9.png)

**Comment by mdrichardson** [comment]
@Talhakh This is expected behavior for nearly all clients and auth services. To disable this in Emulator, uncheck "Use a sign-in verification code for OAuthCards" in Settings:

![image](https://user-images.githubusercontent.com/40401643/65902467-59dc5e00-e36f-11e9-93ac-ef46b3cc1f60.png)


Again, this is expected behavior. It is up to the client/channel (Emulator, Web Chat, Teams, Skype, etc) and the auth source (AAD, Slack, GitHub, etc) to decide whether or not to require the magic code. With AAD auth, nearly every channel requires the magic code. I believe Emulator and Web Chat are the only ones where it can be disabled. It even shows in Teams, but Teams sends the code on its own so--to the user--it doesn't *appear* that a magic code is required.

**Comment by Talhakh** [comment]
@mdrichardson thanks for the clarification 👍
