### ISSUE TITLE
Bot channel registration name is not added before actual value in Activity.Text

### ISSUE THREAD

**Issue by Rashree138** [microsoft/BotBuilder-Samples#1787]
Hi Team,

If we started a chat thread in BOT in Teams then we get the reply hyper link when we click on this link then **Bot channel registration name** is showing in the reply text box.
- Again if user will provide his input then no do not click from Mouse from anywhere in the Teams or Screen, then Bot will reply  in same window, now if user put his input again then no reply from BOT because **Bot channel registration name**  is not added in reply text box.

- If user click anywhere in teams so that focus is lost from Reply text box and then user click again reply hyperlink then **Bot channel registration name**  again displaying text box and this time bot will reply if user provide any input.

**Bot channel registration name** 
![image](https://user-images.githubusercontent.com/13681207/65937869-d1c58980-e43e-11e9-87f8-e7dfb7fb87bb.png)

**Bot channel registration name is not comming** 
![image](https://user-images.githubusercontent.com/13681207/65937909-fde10a80-e43e-11e9-9dc5-c6b87cd5b4ec.png)

My question :
-=============
Is this expected behavior? Because in chat mode in Teams this is not happening.

**Comment by mdrichardson** [comment]
@Rashree138 @ivikashijha (I can't seem to properly tag you. Sorry)

This is intended behavior. When clicking:

![image](https://user-images.githubusercontent.com/40401643/65985807-64622a80-e437-11e9-9a70-4f4bef749114.png)

...you're indicating that you want to reply directly to the user who sent that last message.

After the message is sent, the Reply input box:

![image](https://user-images.githubusercontent.com/40401643/65985848-822f8f80-e437-11e9-9e9b-7eff6b225379.png)


...opens up because you can Reply to *anybody* or *generally* to that conversation thread. 

If you test, you can see that multiple users can join the conversation thread, even though it was started as just between you and the bot. Now, if you use the second Reply input box, the bot won't receive the message, even though it's in that conversation thread, since the bot can *only* receive messages that are either 1:1 or the bot is `@mentioned`. If you think about Teams Channels in a non-bot context, it makes perfect sense for it to behave this way. It just isn't quite as intuitive when you get a bot involved.

**Comment by ivikashjha** [comment]
Thanks
