### ISSUE TITLE
46.TeamsAuth - how to use in Teams

### ISSUE THREAD

**Issue by MarshHawk** [microsoft/BotBuilder-Samples#1816]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]

It is not clear how to test the TeamsAuth bot in Teams. I would think there would be at least some info on using it there. I have successfully deployed TeamsAuth bot and have tested it in the Azure portal chat. Yet, all of the Teams docs seem to be targeting the 3.0 framework, which doesn't run in .Net core. I want to add the bot to an App in app studio and test it there. Is there something out there I've missed that can get me started?

**Comment by jwiley84** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.

That being said, in order to test the Teams Auth sample in Teams, you're going to have to add the Teams channel to your bot via the channels blade in Azure Portal, and then add an app manifest.json to the bot on Teams itself. The Teams team has a well written doc on how to do this [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package). The one thing that is not mentioned is that in order to use OAuth cards, you must ensure you have 'token.botframework.com' in the valid domains. An example manifest.json is below:

```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
  "manifestVersion": "1.3",
  "version": "1.0.0",
  "id": "<APP_ID>",
  "packageName": "com.example.myapp",
  "developer": {
    "name": "MY NAME",
    "websiteUrl": "https://myurl.com/",
    "privacyUrl": "http://web-policies.azurewebsites.net/privacy",
    "termsOfUseUrl": "http://web-policies.azurewebsites.net/terms"
  },
  "name": {
    "short": "Auth Bot"
  },
  "description": {
    "short": "Authentication Bot",
    "full": "Authentication Bot"
  },
  "icons": {
    "outline": "small.png",
    "color": "large.png"
  },
  "accentColor": "#468499",
  "bots": [
    {
      "botId": "<APP_ID>",
      "scopes": [
        "team",
        "personal",
        "groupchat"
      ],
      "supportsFiles": true
    }
  ],
  "validDomains": [
    "token.botframework.com"
  ]
}
```

**Comment by MarshHawk** [comment]
@jwiley84 thanks for the clarification on the valid domains, if I run into any further mysteries I will port information to stackoverflow
