### ISSUE TITLE
Unable to send file as an attachment in skype

### ISSUE THREAD

**Issue by niharikabhavaraju** [Microsoft/BotBuilder-Samples#184]
### SDK Platform

.NET
### Problem Description

Im unable to send file as an attachment in skype from bot to user.
Im specifying the contenturl of the file,it is working fine in emulator but not in skype.
```cs
 private static Attachment GetInternetAttachment()
        {
            return new Attachment
            {
      Name = "SampleDOCFile_100kb.doc",
                ContentType = "application/msword",
          ContentUrl = "https://drive.google.com/uc?id=0B129OIZ80bZfSVdoLVN2clByNXc&export=download",
             };
        }
```

**Comment by IoTGirl** [comment]
Hi @niharikabhavaraju 

I am new to the Bot Framework but it looks like there is some sample information available to you at [https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-media-attachments](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-media-attachments)

Specifically, the definition of the content is different than your code above.  
`replyMessage.Attachments.Add(new Attachment()
{
    ContentUrl = "https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png",
    ContentType = "image/png",
    Name = "Bender_Rodriguez.png"      
});`

The sample code indicates  to add the attachment to the message rather than the instantiation you are using.

Sincerely,
IoTGirl

**Comment by CoHealer** [comment]
Closing, received no response
