### ISSUE TITLE
[bug bash] Multiple qnamaker samples and no differentiation in the folder name or readme description for the bot

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotBuilder-Samples#1932]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
There are multiple qnamaker samples and it's not clear what the differences among the samples from the folder/project name or project description in the readme.

https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11.qnamaker
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11a.qnamaker
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/49.qnamaker-all-features

Can we use the same naming convention as this qna bot sample?
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/48.qnamaker-active-learning-bot

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by johnataylor** [comment]
We are in the process of reviewing the QnA samples.

11a was a temporary solution because we wanted to make sure the super simple 11 was still available for developers to reference.

So now 11 is back as it was. And we have 48 and 49. We're working with the QnA team to consolidate and also make sure all the features are demonstrated.
