### ISSUE TITLE
[bug bash] Need more instructions on running and testing the bot with LUIS/QnA

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotBuilder-Samples#1945]
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
There are few steps missing and really needed to be done before one could run the bot.  For c# bots, the fields for LUIS/QnA settings in appsettings.json file need to be populated.  For JS/Typescript bots, the same fields in .env file need to be populated.  Furthermore, we need examples for how the fields "QnAEndpointHostName",  "LuisAPIHostName" should look like.  I recall some needs "https://" prefix, some don't for host name, depending how the helper class forms the URL.  

Without updating the fields properly, nothing could be tested.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by penguintechlinux** [comment]
To Reproduce
Steps to reproduce the behavior:

Build the application and then in chat emulator type any message . .
Using debugger , its failing at FlightBookingRecognizer.cs at below line:-

   public virtual async Task<T> RecognizeAsync<T>(ITurnContext turnContext, CancellationToken cancellationToken)
            where T : IRecognizerConvert, new()
            => await _recognizer.RecognizeAsync<T>(turnContext, cancellationToken);



Screenshots
If applicable, add screenshots to help explain your problem.

Additional context
Add any other context about the problem here.
<img width="950" alt="boterror" src="https://user-images.githubusercontent.com/53962948/74450387-fe38ea00-4ea3-11ea-8327-5773fe8ac88d.PNG">

[bug]

**Comment by garypretty** [comment]
Review of this sample and update of readme taking place as part of https://github.com/microsoft/botframework-sdk/issues/5897
