### ISSUE TITLE
Welcome card is not displayed when CoreBot sample is deployed to Azure

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotBuilder-Samples#1993]
I'm using CoreBot template with no changes and deployed it to azure using instructions.
Bot works fine locally but not when Deployed - welcome card is not displayed.
It generates an exception when trying to display an Adaptive card as a welcome message:
Here is the exception from the log:
**[Error] Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter: [OnTurnError] unhandled error : Value cannot be null.Parameter name: stream**
![Bot error](https://user-images.githubusercontent.com/20775323/69075355-da761d00-09f6-11ea-8bae-6d09939288e3.png)

**Comment by turbozapekanka** [comment]
I bet the issue is with CreateAdaptiveCardAttachment method where it tried to load the welcomeCard.json but cant do that for some reason resulting in non-initialized stream variable.

**Comment by turbozapekanka** [comment]
This might be a deployment issue, I just logged via FTP and see no Cards folder on the server.
But even if I copy the folder over it does not work.

![Cards missing](https://user-images.githubusercontent.com/20775323/69091096-364ca000-0a0f-11ea-9174-a6791f4287ae.PNG)

**Comment by v-kydela** [comment]
@turbozapekanka - I'm guessing when you say CoreBot template you mean the CoreBot .NET sample from this repo. Is that correct?

I believe you will find when you examine your local bin folder that the card is not present there either, meaning the lack of card has nothing to do with deployment. This is because the card file is an embedded resource and you can see in its properties that it's not supposed to be copied to the output directory:

![image](https://user-images.githubusercontent.com/41968495/69198671-4d13f500-0aea-11ea-9eac-a57ef5070427.png)

Perhaps the card resource has to be accessed differently in your deployed environment. Can you provide some details about the app service you're deploying to?

**Comment by turbozapekanka** [comment]
I meant this template: https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4
I guess it is the same, maybe slightly older version.
I'm deploying to the Azure using these instructions (the're also referenced in the template default.html file)
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp

I would expect the sample code work with both Local and Deployed environments, that's why I reported it.
I had to change the code to use file reader as I found in another examples.
Just wondering what's wrong with this code using embedded resources and why it does not work when deployed.

**Comment by v-kydela** [comment]
@turbozapekanka - That link contains four templates. Did you use Core Bot or Core Bot with Tests?

**Comment by turbozapekanka** [comment]
Core bot

**Comment by v-kydela** [comment]
@turbozapekanka - I have determined the cause of the problem here. The deployment process changes the name of your assembly to lower case:

![image](https://user-images.githubusercontent.com/41968495/69468886-ef2e1a00-0d42-11ea-8271-3dc1965c1165.png)

That means the card resource path won't work since the hard-coded assembly name is camel case:

```c#
var cardResourcePath = "CoreBot1.Cards.welcomeCard.json";
```

I believe changing the code to this will fix the problem:

```c#
var assembly = GetType().Assembly;
var cardResourcePath = $"{assembly.GetName().Name}.Cards.welcomeCard.json";

using (var stream = assembly.GetManifestResourceStream(cardResourcePath))
```

It's unclear to me where in the deployment process the name change occurs, and whether this should be considered a bug in the deployment process or just a bug in the template. To me this name change seems undesirable, though it may be necessary for reasons unknown to me. @sgellock - Can you advise?

**Comment by v-kydela** [comment]
@turbozapekanka 

I have just tested [an alternative deployment method](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip#deploy-zip-file) and it still changes the assembly name to lowercase.

I have discovered that the conversion to lowercase is happening in the `az bot prepare-deploy` command. I have logged that bug here: https://github.com/Azure/azure-cli/issues/11390

This suggests another workaround you can use. If you manually change the name of your assembly in your .deployment file to the correct name _after_ running `az bot prepare-deploy` and _before_ zipping your project folder then your deployment should work.

Because the bug has been logged in the appropriate repo and workarounds have been given, I am considering this issue resolved.

**Comment by v-kydela** [comment]
I want to note that publishing through Visual Studio does not have this problem, and so it can be considered another workaround.
