### ISSUE TITLE
Documentation out of date LuisActionDialog Obsolete

### ISSUE THREAD

**Issue by JamieG** [Microsoft/BotBuilder-Samples#206]
### SDK Platform
.Net

### URL of Code Sample
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/Blog-LUISActionBinding

### Problem Description
All documentation I can find relating to Action Binding references LuisActionDialog'. In the current version of the Microsoft.Bot.Builder 3.11.0 this class is marked as Obsolete with a fairly cryptic message of 'Action binding in LUIS should be replaced with code.' from the documentation I thought that this was what this class was doing, delegating the action to code? The fact this class is now obsolete does not seem to be reflected in any documentation I can find. Is there an example of the recommended approach to action binding that does not use this dialog anywhere?

It's also fairly frustrating that the released version of the Bot Framework is 3.11.0 whilst all the documentation and the source code itself seems to be version 3.8.0.0, why is the source and documentation so out of date?

**Comment by EricDahlvang** [comment]
Hi @JamieG 

Thank you for taking the time to bring this to our attention.  It is a bit confusing because the LuisActionDialog in the Bot Builder SDK has been deprecated: https://github.com/Microsoft/BotBuilder/blob/b6cd3ff85e8dc57ac586a11db489a0c75c635ae2/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs

However, the sample you referenced is actually using a different LUISActionBinding library that has not been pushed to the Cognitive Services nuget package yet.  There is a pull request for it here: https://github.com/Microsoft/BotBuilder-CognitiveServices/pull/35  Until this is merged, the only way to use the LUISActionBindings library is to download the source and reference it in your project directly.

We apologize if the documentation seems out of date in places.  We try to keep these things current as the sdk goes through iterative changes.  If you find any other discrepancies, please report them here or on the Bot Builder repository: https://github.com/Microsoft/BotBuilder

**Comment by EricDahlvang** [comment]
Luis Action Binding library is now in this repository: https://github.com/Microsoft/BotBuilder-CognitiveServices
