### ISSUE TITLE
Invalid Signature while authenticating JWT token

### ISSUE THREAD

**Issue by krisalay** [microsoft/BotBuilder-Samples#2138]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [nodejs]
3. Sample name: teams-auth

## Describe the bug
I received the JWT token after login from microsoft. But when I put the JWT token at jwt.io, it gives invalid signature.

## To Reproduce
1. Get the JWT token after authentication
2. Copy the JWT token
3. Go to jwt.io website
4. Paster the token

## Expected behavior
Signature should be verified

[bug]

**Comment by stevkan** [comment]
@krisalay, technically, I was able to repro this issue using a token generated from an AAD OAuth2 connection in my bot's Azure settings while running sample "46.teams-auth". I verified that the value of "x5t" property in the algorithm header matched the x5t value located in the openid-configuration => keys endpoint, so the correct connection was being called. However, whether using the generated public key or passing in the private key, it still returned an "invalid signature".

Microsoft docs regarding token signatures state Azure AD tokens are issued using an asymmetric encryption algorithm, such as RS256 (as opposed to HS256). I mention this only because testing the token (+ key) on jwt.io using HS256 appears to produce a valid signature.

I decided to test a token generated from the Microsoft Graph Explorer. (When logged in and in the developer's console, you can type "tokenPlease()" and a token will be generated.) Interestingly, this also showed as "invalid".

I decided to verify the Teams/Web Chat tokens using a different site (https://www.jsonwebtoken.io/). When I passed the tokens with either the generated public key (taken from jwt.io) or the private key, it shows as a valid signature.

The short of it is, I'm not certain this is a bug with the token or with the jwt.io site. If you could test a token on the above site and report back, that would be great.

**Comment by krisalay** [comment]
@stevkan I tested the token on jwt.io as well as jsonwebtoken.io. At both the websites, I am getting invalid signature. 
Also, when I am making an api call to https://graph.microsoft.com/v1.0/me/ with the JWT token in authorization header, I am able to get the response back, it means the token is getting validated on the microsoft side. 
But the validation is failing (invalid signature) with any JWT package either in nodejs or php.

**Comment by Virtual-Josh** [comment]
hey @stevkan can you provide an update on this ticket?

**Comment by stevkan** [comment]
@krisalay, can you verify for me the `typ` that is returned in the header of the token when you test it on jwi.io (or elsewhere)? I want to make sure it is, in fact, a 'JWT' token.

As for the JWT test sites, they both are reporting invalid for me, now. I'm not sure what was happening the other day, but it's now in line with your experience.

Also, you say you get the JWT token after logging in to Microsoft. Is this an AAD or an MSA (Microsoft Account...Hotmail, Outlook)? And, I'm assuming this is after clicking a login button as part of the chat dialog with the bot?

If the token you are referring to does come from clicking on a login button and signing in, then the issue of an invalid signature on a token wouldn't be a Bot Framework issue. The reason being is the bot simply utilizes the token that is retrieved from the provider and is not responsible for the token generation. If this is the case, then you would need to file the issue with that provider.

Given the above, your issue may be related to [this one](https://github.com/MicrosoftDocs/azure-docs/issues/46531).

**Comment by CoHealer** [comment]
@krisalay, do you still require assistance?

**Comment by stevkan** [comment]
Closing due to a lack of response. If the issue persists or you have new information to provide, please feel free to reopen.
