### ISSUE TITLE
Multi language bot

### ISSUE THREAD

**Issue by deepumi** [Microsoft/BotBuilder-Samples#214]
Any sample application for Multi Language bot?. I am trying to build Multilingual bots for English & Spanish version. 

Any documentations or samples links would be appreciated.

**Comment by FranciscoPonceGomez** [comment]
Hi @deepumi,

For translating back and for to different languages you can use Microsoft Translator API and call it like this (First you need to register and get a token):

"http://api.microsofttranslator.com/v2/Http.svc/Translate";

Take a look at my translator class. It utilizes an API to detect the language and another to translate to English and back to the original language. But since you are only translating from and to Spanish you can pass the language code in the parameter:

var accessToken = await Translator.GetAuthenticationToken(ConfigurationManager.AppSettings["TranslatorApiKey"]).ConfigureAwait(false);
                        reply.Text = await Translator.TranslateText(answer, "es", accessToken).ConfigureAwait(false);

https://github.com/FranciscoPonceGomez/QnATranslatorSample/blob/master/QnATranslatorSample/Utils/Translator.cs

Regards,
Francisco

**Comment by deepumi** [comment]
Thanks @FranciscoPonceGomez 

We do have a third party service which does translation service, Can we integrate our own translation service instead of Microsoft Translator? If so, is it possible to get CurrentCulture in bot API for "es" "en" ?

**Comment by FranciscoPonceGomez** [comment]
You can add any translator to your bot logic. If your translation service exposes a public API that the bot can call, then is just a matter of sending the message text from the activity to the translator like I did in the example:
```cs
string answer = result.Answers.First().Answer;
            Activity reply = ((Activity)context.Activity).CreateReply();
reply.Text = YourCustomTranslator(answer);
```
If your third party service doesn't provide an API then you might need to write a wrapper or a client to be consumed by your bot. 
Microsoft Bot Framework doesn't impose any translation service. You can use your own.

Regards,
Francisco
