### ISSUE TITLE
Hand Off Documentation missing

### ISSUE THREAD

**Issue by elcaytuiro** [microsoft/BotBuilder-Samples#2166]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[How can I Test HandOff Bot ? ] 

In the repo https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library    
Only show how to implement the handoff in your bot, but does not show How can I test the bot. I think that We need 2 bots. Is completed the code sample ? 

Do we need to create 2 bots? ...  Where Can I see the user request for human asistant

**Comment by jwiley84** [comment]
HI @elcaytuiro 

The Handoff sample is still in development, which is why it lives in the experimental branch of the repo. The readme is not complete in it's instructions, because the sample is actively being worked and altered. The last update on that sample was just over a week ago. 

Please keep monitoring the sample for updates, and let us know if you have any questions about any of the official samples!
