### ISSUE TITLE
Alternative for WaterfallStepContext in adaptive dialog

### ISSUE THREAD

**Issue by deenaMaistering** [microsoft/BotBuilder-Samples#2179]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
I have been using WaterallStepContext.Context.Activity.From.Id to get the email address of the User. But I couldn't figure out what to use to get the same in an adaptive dialog.

**Comment by mdrichardson** [comment]
@deenaMaistering You use `turn.activity.from.id`. For example, I took the [Adaptive Multi Turn Prompt Sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/csharp_dotnetcore/02.multi-turn-prompt), and I added:

```csharp
new SendActivity("User: @{turn.activity.from.id}"),
```

[here](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/csharp_dotnetcore/02.multi-turn-prompt/Dialogs/RootDialog.cs#L67):

```csharp
private static List<Dialog> WelcomeUserSteps()
{
    return new List<Dialog>()
    {
        // Iterate through membersAdded list and greet user added to the conversation.
        new Foreach()
        {
            ItemsProperty = "turn.activity.membersAdded",
            Actions = new List<Dialog>()
            {
                // Note: Some channels send two conversation update events - one for the Bot added to the conversation and another for user.
                // Filter cases where the bot itself is the recipient of the message. 
                new IfCondition()
                {
                    Condition = "$foreach.value.name != turn.activity.recipient.name",
                    Actions = new List<Dialog>()
                    {
                        new SendActivity("User: @{turn.activity.from.id}"),
                        new SendActivity("Hello, I'm the multi-turn prompt bot. Please send a message to get started!")
                    }
                }
            }
        }
    };

}
```

...so that when I set my User ID in Emulator:

![image](https://user-images.githubusercontent.com/40401643/74051365-a6265300-498c-11ea-84e0-97064def2d21.png)

I get:

![image](https://user-images.githubusercontent.com/40401643/74051377-ade5f780-498c-11ea-9049-b7d62c16895e.png)

That being said, the Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.
