### ISSUE TITLE
composeExtensions[0].commands is required

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2322]
According to the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet#manually) `composeExtensions.commands` is an optional field. But I'm trying to install application where commands field is omitted or empty `[]` I'm getting an error that `composeExtensions[0].commands is required`. What's the proper value for the commands field?

**Comment by axelsrz** [comment]
Hey @jwiley84 could you investigate further on this to know if this is a docs or sample issue? Thanks.

**Comment by clearab** [comment]
Unfortunately, it currently isn't possible to create an app with a messaging extension that only includes link unfurling. This bug should be resolved is currently being worked on and should be resolved soon.

Right now, you'll need to add a messaging extension command to your App Manifest in order to install it. I would recommend trying a search command, as they are the closest in implementation to link unfurling.

**Comment by GDreyV** [comment]
Thanks, for now I added logout command. I just wanted to check if you aware about it. Thank you for fast reply.
