### ISSUE TITLE
How to send hero cards , adaptive cards,links as responces to bot integrated in slack channel using  IBotFrameworkHttpAdapter.

### ISSUE THREAD

**Issue by kittu610** [microsoft/BotBuilder-Samples#2330]
How to handle attachment in bot which is integrated in slack channel

i was trying to send hero cards and adaptive cards but i am getting an error like "The bot encountered an error" in bot.

Please can you suggest me how to handle cards and links in bot integrated in slack. 
by using IBotFrameworkHttpAdapter. in csharp_dotnetcore.

**Comment by v-kydela** [comment]
Hi @kittu610 

Can you show us what you've tried so far? Are you following a specific sample?

**Comment by kittu610** [comment]
Hi @v-kydela 

I have created an bot using Bot Framework V4
By referring [this link ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp) i have created an hero card 
By referring [this link ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs) i ave deployed my bot in azure and created an slack app

**Comment by v-kydela** [comment]
@kittu610 - Slack does not support Adaptive Cards. You can see which platforms support Adaptive Cards here: https://docs.microsoft.com/en-us/adaptive-cards/resources/partners

If you want to be able to send hero cards to Slack, you need to be using the Azure Bot Service and not the Slack adapter. You linked to a document that explains how to use both but you haven't specified which option you're using or how your bot is set up. You say you want to use `IBotFrameworkHttpAdapter` but `SlackAdapter` implements `IBotFrameworkHttpAdapter` so that doesn't give us the information we need. Please let us know what adapter you're using and post the code you're using to send the hero card that's throwing the error.

**Comment by kittu610** [comment]
[Nameforslack.zip](https://github.com/microsoft/BotBuilder-Samples/files/4516297/Nameforslack.zip)

**Comment by v-kydela** [comment]
@kittu610 - Looking at your code, I can see that you're using a Slack adapter. Were you unaware of this? Did you use sample 60? https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/60.slack-adapter

**Comment by kittu610** [comment]
Hi @v-kydela 
I have created a bot using echo bot template and modified the code by following [This link](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=adapter#tabpanel_CeZOj-G++Q_adapter)
And then i have referred https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/60.slack-adapter how to send attachment to slack

**Comment by v-kydela** [comment]
@kittu610 - Do you understand the difference between using the Slack adapter and the Azure Bot Service Slack channel connector? Do you know which one you want to use and why? I need to know what your point of confusion is so that I know what I need to explain in order to help you. I already explained that you cannot send hero cards using the Slack adapter.

**Comment by v-kydela** [comment]
@kittu610 - Are you still working on this?

**Comment by v-kydela** [comment]
I'm going to close this due to inactivity. To reiterate, Adaptive Cards are not supported on Slack, and Bot Framework rich cards can only be used on third-party channels if you're using an Azure Bot Service channel connector and not an adapter.
