### ISSUE TITLE
Handle adaptive card sent to the bot

### ISSUE THREAD

**Issue by GDreyV** [microsoft/BotBuilder-Samples#2338]
Hello! I can't find any examples how to parse adaptive cards sent to the bot in the personal chat with that bot:
1. How to understand that the message is a card?
2. How to get meta information about that card? Who composed that card (what bot)? How to get buttons/actions with bound values and action types?

**Comment by v-kydela** [comment]
Hi @GDreyV - I would like to help but I have a few questions.

1. When you arrive at the [new issue page](https://github.com/microsoft/BotBuilder-Samples/issues/new/choose), what option are you choosing?
1. Are you developing a bot or a channel client?
1. What channel are you using?
1. What programming language are you using?
1. Since you're posting in the samples repo, are you following a specific sample?
1. When you say "parse adaptive cards" do you mean read Adaptive Card JSON and convert it into a runtime object?
1. What do you mean by "adaptive cards sent to the bot"? Cards are meant to be sent _by_ the bot _to_ the user.

Also, please post a screenshot/gif to help us understand the issue you're facing

**Comment by GDreyV** [comment]
1. I got you, for current case I should choose create new Question, my fault, sorry about that.
2. I'm working on the bot like in the example https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config
3. I suppose Teams channel, did I get you right?
4. it's C#
5. I'm following example 52.teams-messaging-extensions-search-auth-config
6. Example 52 creates adaptive card in compose message block. User can send this card back to bot just by pressing send button. In that case handler `protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity>, CancellationToken)` is fired. And I need to understand if the message is a card and get details of that card. Runtime object will be perfect, but json also will work.
7. You are right. But when user runs compose extension query command bot produces adaptive card which is not sent but placed into the compose message block. So it can be sent to anybody including conversation with bot. Also bot can be mentioned in that message.

**Comment by v-kydela** [comment]
@GDreyV - Yes, you did get me right. Thank you for the answers.

In your second question, you ask how to get metadata about the card including the bot that composed the card. Are you in a conversation with a bot while using messaging extensions from multiple other bots?

**Comment by GDreyV** [comment]
Correct me if I'm wrong but if user has 1-to-1 conversation with the bot user can use compose extension command provided by different bot and send card built by that bot into the chat. So I need to identify who created the card and should I process it somehow or not.
Just to add some background to the flow. I was asked by the certification team to support flow when card was sent to the bot but I didn't manage to find any examples of such flow, specifically how to handle incoming cards while messaging.

**Comment by GDreyV** [comment]
@v-kydela, sorry to disturb you, if you can say that it's impossible for now it will work for us because right now we just stuck with certification because of requirements which we don't know how to implement.

**Comment by v-kydela** [comment]
@GDreyV - I have no reason to believe it's impossible, but I cannot work on your issue because I don't have access to a Teams tenant where I can install app manifests. I'm transferring this to a colleague.

**Comment by stevkan** [comment]
@GDreyV, I just want to make sure I'm caught up on what you are wanting. In a 1:1 conversation between a user and your bot, you want to be able to capture any card attachment meta data sent back to the bot from a messaging extension in order to identify where the card originated from, correct? To be able to tell if the card returned came from your bot, Bing News, GitHub, or any other bot/app messaging extension the user has installed and is interacting with?

If this is so, the card returned to the bot from the messaging extension is, as you guessed, an activity type of "message". The activity attachment property contains the generated card. You can access this via OnTurnAsync or one of the other regular or Teams specific activity handlers in your bot.

Does this help or did I shoot wide of the mark?

**Comment by GDreyV** [comment]
You are completely right. Except the point it's requested by certification team instead of wanted by us :) I found what you are talking about but it's still not clear how to find actions and values bound to the buttons and who (what bot) composed the card.
So here's the card:
![image](https://user-images.githubusercontent.com/6262948/80431413-60a86080-88bf-11ea-84cf-71feec33b2eb.png)
And here's what is in attachment:
```html
<div><div><span itemid="f0650b815a114f31a7c238c7dca7b1cd" itemscope="" itemtype="http://schema.skype.com/InputExtension"><span itemprop="cardId"></span>
<div title="">
<div>
<div>
<div>&nbsp;</div>
</div>
<div>
<div>
<div style="background-image:"><img alt="Artboard 1" src="https://urlp.asm.skype.com/v1/url/content?url=https...preview.png" style="width:169px; height:300px"></div>
</div>
<div>
<div>
<div title="SMP-5706">SMP-5706</div>
<div title="3 designs">3 designs</div>
</div>
</div>
</div>
<div>OpenSubscribe</div>
  </div>
</div>
</span></div>
</div>
```

**Comment by v-kydela** [comment]
`Activity.Attachments` is an `IList<Attachment>`. It has no `Items` property, and if it did then it would give you an `Attachment` object and not an HTML string. So that can't be right.

**Comment by GDreyV** [comment]
You are completely right. Items is a property from Debug view. So what property should I check?
![image](https://user-images.githubusercontent.com/6262948/80528844-95babe80-8964-11ea-960f-09327af22d89.png)

**Comment by v-kydela** [comment]
Okay, that's what we needed to see. That HTML was in the content property of the attachment, and the type is text/html instead of a card type. Also, it looks like the HTML is sanitized to remove the button elements etc., so it will be very difficult for you to include any hidden metadata in the card that will show up in the HTML the bot receives.

**Comment by GDreyV** [comment]
Am I getting it right that for now there is no api to obtain adaptive card details from activity and the only way to understand that message content is a card is try to parse html?

**Comment by stevkan** [comment]
Unfortunately, no, at this time there does not appear to be any API or other method beyond what you already see and know. You may want to check out [Microsoft Graph](https://developer.microsoft.com/en-us/graph/graph-explorer). There are some Teams APIs that are available that you may be able to put to use by integrating into your bot. I haven't checked the APIs out too closely, but with the correct permissions and the correct meta data (group Id, channel Id, etc.) you could possibly get the returned messaging extension activity. This could be easier than parsing the HTML.

I'm going to go ahead and close this issue as resolved, in the mean time.
