### ISSUE TITLE
dotenv loads before loading bot

### ISSUE THREAD

**Issue by GeekTrainer** [microsoft/BotBuilder-Samples#2374]
## Sample information
1. Sample type: samples (yeoman generator)
2. Sample language: typescript
3. Sample name: yeoman generator

## Describe the bug
The call to load .env variables is after the load of **bot.ts**. As a result, the environmental variables aren't set, so accessing them in **bot.ts** fails.

## To Reproduce
1. Add a call to `process.env` in **bot.ts**
2. Try to use the value

## Expected behavior
The value should be loaded

## Additional context

[bug]

**Comment by stevengum** [comment]
@Zerryth, can you validate his PR by cloning his changes into the JS and TS core bot samples?

When validation is complete, please also clone the changes to JS generator core-bot.

**Comment by Zerryth** [comment]
Roger that

**Comment by Zerryth** [comment]
@GeekTrainer perhaps you could provide more precise repro steps as to how you got it to break, because I am unable to repro the bug.

___

**What I did to try to repro the issue**:
1. Follow the installation instructions given in the [`generator-botbuilder README`](https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder#installation) to get yeoman botbuilder
2. Created a TS corebot using `yo botbuilder` command
3. Editing corebot:
   * Add LUIS credentials to .env
   *  Edited the `dialogBot.ts` to use `process.env` as you specified. I just did a simple console.log in the `onMessage` handler
         ```js
            this.onMessage(async (context, next) => {
                console.log('Running dialog with Message Activity.');
                console.log('************************************');
                const { LuisAppId, LuisAPIKey, LuisAPIHostName } = process.env;
                console.log('process.env LuisAppId', LuisAppId);
                console.log('process.env LuisAPIKey', LuisAPIKey);
                console.log('process.env LuisAPIHostName', LuisAPIHostName);
                console.log('************************************');
         ```
4. `npm i` and `npm start` to run the bot

The following results yielded values when I send a message to corebot, even though `index.ts`:
*console*
![image](https://user-images.githubusercontent.com/35248895/81884963-2e009800-954e-11ea-802a-97ec03b96932.png)

*index.ts*
![image](https://user-images.githubusercontent.com/35248895/81885068-63a58100-954e-11ea-8d49-bef80bf339b8.png)

**Comment by Zerryth** [comment]
Got it to break! Hooray! (?) 😄

**Comment by Zerryth** [comment]
Reopening for Part II of this issue to ensure the changes to load .env variables earlier than bot are carried over into the other templates: [PR#2403](https://github.com/microsoft/BotBuilder-Samples/pull/2403)
