### ISSUE TITLE
Python samples: proactive messages are sent to only the first user

### ISSUE THREAD

**Issue by khaelys** [microsoft/BotBuilder-Samples#2412]
## To Reproduce
1. Run proactive messages python sample
2. Open two chats
3. Call the GET endpoint http://localhost:3978/api/notify
4. The message will be sent only to the first chat user

## Expected behavior
Expect that all chat will receive the proactive message

[bug]

**Comment by tracyboehrer** [comment]
@khaelys Thanks!  This is because the person who wrote it (me) clearly didn't have enough coffee that morning.

In the app.py, in the _send_proactive_message function, remove the "return" on the "ADAPTER.continue_conversation" call.

Should look like this:

```
async def _send_proactive_message():
    for conversation_reference in CONVERSATION_REFERENCES.values():
        await ADAPTER.continue_conversation(
            conversation_reference,
            lambda turn_context: turn_context.send_activity("proactive hello"),
            APP_ID,
        )
```

I will submit a real fix for this shortly.
