### ISSUE TITLE
How to set connection using certificate

### ISSUE THREAD

**Issue by csbo** [microsoft/BotBuilder-Samples#2434]
According to the advice from your people, my problem is legitimate here.

In short, I want to get user token with first party app.

Currently, I am following this doc ([Add authentication to a bot](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0)) to register a first party app as the identity application with the bot using connection.

In my understanding, after I setting the connection, I can easily get user token following these two samples ([Bot authentication](https://aka.ms/v4cs-bot-auth-sample) or [Bot authentication MSGraph](https://aka.ms/v4cs-auth-msgraph-sample)) and using `ConnectionName` in code. 

 
Now the problem is that first party app only provide certificate not secret. So I cannot set the connection in Azure portal following that doc. 

My question is:
- Can I set the connection in code or somewhere? 
- If not, can I get user token with first party app by some other ways?
- If still not, can I get user email address? (My channel is only Teams)

Thanks for help.

**Comment by carlosscastro** [comment]
@swagatmishra2007 or @Jeffders any thoughts on this? I don't know that we've ever tried this or whether we support it given that 1P app secret is only cert based.

**Comment by carlosscastro** [comment]
Hello @csbo , I checked with the other oauth experts and this is not supported, and there is no workaround for this at the moment. Thanks to your comment, we'll start brainstorming future paths to support this but there is some inherent complexity to it.

In the meantime, 2 potential ways of going forward (none ideal unfortunately, but they should unblock you):

1) Use a non-first party app. Depending on the kind of software you are working on, this may not be a possibility from a compliance point of view. But if it is within the compliance boundaries, you could have an app just to do this auth.
2) Check out our OAuthPrompt code which is publically available [here](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs), and create your own version but instead of calling the token service, craft your own sign in link using your first party app and send it in the card. You'd also need to be careful with the redirect uri to make sure the tokens reach your bot properly. Feel free to contact me over email for more details on this.

Closing for now, but feel free to reopen if you have comments or questions from which the community would benefit :)

**Comment by swagatmishra2007** [comment]
a third option would be to implement your own oauth provider that would wrap around the first party auth and register that as a generic oauth2 provider on the portal. It would involve implemeting a couple of api routes - one to get tokens (which internally would get a token for your first party app) and another for refresh. this is what we do internally for testing the service, so feel free to reach out us via email (my alias - swagatm)
