### ISSUE TITLE
Calling a method/callback after adaptive card's Action.OpenUrl operation

### ISSUE THREAD

**Issue by prasanth-rgmobiles** [Microsoft/BotBuilder-Samples#245]
Hello, 
I'm using adaptive card to show an article to user in node js.
**My Adaptive card format:**
`function AdaptCard (Txt, Img, Url) {
        let cardFormat = {
            contentType: "application/vnd.microsoft.card.adaptive",
            content: {
                "type": "AdaptiveCard",
                "version": "1.0",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": Txt,
                        "size": "medium",
                        "weight": "bolder",
                        "wrap": true
                    },
                    {
                        "type": "Image",
                        "url": Img,
                        "size": "auto"
                    }
                ],
                "actions": [
                    {
                        "type": "Action.OpenUrl",
                        "title": "View Article",
                        "url": Url
                    }
                ]
            }
        };
        return cardFormat;
    }`
**Session Code:**
`
bot.beginDialog(message.address, 'ShowArticle');
bot.dialog('ShowArticle', [
    (session) => {
        let dispCard = new builder.Message(session).addAttachment(AdaptCard (
            "Title",
            "Image URL",
            "Link URL"
        ));
        session.send(dispCard );
    }
]);`
I'm trying to ask a user that if the url provided is useful?, after he visits the article.
Is there any event like **bot.on('some event')** that i can use once the user does **Action.OpenUrl**?

Need help pls.

**Comment by linach** [comment]
Hello, I have a similar scenario. I would like to define a callback to be executed after Action.Submit. 
For example hide the adaptive card.

**Comment by EricDahlvang** [comment]
Since the client side code responds to the OpenUrl, there is no way to know when or if the user has clicked it.  However, you can provide a parameterized endpoint and redirect to the intended url.  Based on the paramter server side, a proactive message could be sent to the user from the bot.  More on proactive messaging can be found here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message   

Some Bot Builder V3 node and dotnet sdk examples of a hero card button redirect can be found here: https://github.com/JasonSowers/BF-302RedirectExample

---

When the user clicks Submit, the bot will receive a message where the .Value property contains json with the values from the adaptive card.  Some examples can be found here: 
 - https://github.com/Microsoft/BotBuilder-Samples/blob/v3-sdk-samples/Node/cards-AdaptiveCards/app.js#L31 
 - https://stackoverflow.com/a/54993920/86646 
 - https://stackoverflow.com/a/52004534/86646 

Hiding the adaptive card would be a client side implementation issue.  Some channels might allow you to send an update activity, that modifies the card within the chat stream.
