### ISSUE TITLE
Only one variation for a Language Generation Template is used.

### ISSUE THREAD

**Issue by roberi** [microsoft/BotBuilder-Samples#2451]
## Sample information
1. Sample type: BotBuilder-Samples/samples/javascript_nodejs/language-generation/05.multi-turn-prompt/
2. Sample language: nodejs, typescript
3. Sample name: multi turn prompt sample

## Describe the bug
When using multiple variations for a Template (LG) only one is used when calling Templates.evaluate. The variation used is selected randomly at the first call to evaluate. This is fine, but all subsequent calls uses the same variation as the first call used.

Both in the Bot Emulator and in MS Teams (side loaded app) this is the behavior when running the bot. Only if the bot/conversation is restarted a new variation is randomly selected (but again the same variation is always used in subsequent calls).

## To Reproduce
1. Follow the instructions in the sample to clone the repo and install the modules.
2. Add a couple of variations to the ModeOfTransportPrompt template in Resources / UserProfileDialog.LG. Ex:

```
# ModeOfTransportPrompt
- Please enter your mode of transport.
- What is your mode of transport?
- How would you like to travel?
```

3. Run the bot in the emulator.
4. Write something to start the dialog.
5. The bot replies with one of the variations above.
6. Write a mode of transport that is not in the list.
7. As you can see the same text is used.
8. Write another mode of transport that is not in the list.
9. Once again the bot replies with the same text.
10. And so on...

## Expected behavior
Each time we call evaluate (see ex below) a new variation should randomly be selected.

```
async transportStep(step) {
  // WaterfallStep always finishes with the end of the Waterfall or with another dialog; here it is a Prompt Dialog.
  // Running a prompt here means the next WaterfallStep will be run when the users response is received.
  return await step.prompt(CHOICE_PROMPT, {
    prompt: ActivityFactory.fromObject(this.lgTemplates.evaluate('ModeOfTransportPrompt')),
    choices: ChoiceFactory.toChoices(['Car', 'Bus', 'Bicycle'])
  });
}
```

## Additional context
I am using v10.19.0 of Node and ~4.9.1 of botbuilder, botbuilder-dialogs and botbuilder-lg in my package.json.

I am not sure if this is a bug or if it is the intended way of how this should work. But I think that a new variation/text should be selected for each call to evaluate if there are more then one variation for a template.

[bug]

**Comment by v-kydela** [comment]
Thank you for the report, @roberi

The behavior you're encountering has nothing to do with language generation and it is by design. When you call `step.prompt` you're adding the prompt onto the dialog stack while passing prompt options that get stored in the dialog state. Since the prompt becomes the active dialog, subsequent turns will continue that dialog and it will reprompt if it needs to using its saved prompt options. Since you only call `this.lgTemplates.evaluate('ModeOfTransportPrompt')` once at the beginning, it will only "evaluate" once which means it will only pick a random option once. If `transportStep` is run again and the prompt gets added to the stack again then it should pick a new option, but the prompt itself doesn't know anything about the `evaluate` function and so it can't call it on subsequent turns. I can think of a few solutions for you.

1. An easy way to gain variety when reprompting is to use the prompt options' [`retryPrompt`](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/promptoptions?view=botbuilder-ts-latest#retryprompt) property. It can be a string or an activity just like the `prompt` property, but since it's not a function it will be the same every time you reprompt.
1. You could reprompt manually by calling `evaluate` from inside a [validator function](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?tabs=javascript#definition-of-a-prompt-validator-method). This would automatically prevent the prompt from reprompting, since `dc.context.responded` would be `true`.
1. You could create a "loop step" in the waterfall so that `evaluate` gets called each turn when the step is looped back to. There's an example of a loop step in [this sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/43.complex-dialog/dialogs/reviewSelectionDialog.js). The sample shows looping by replacing the whole dialog, but you can also step backwards by modifying the waterfall's step index. Since you want the prompt to end rather than reprompt for invalid input, you wouldn't be able to use a choice prompt. You'd either use a text prompt or no prompt at all. This solution could get tricky.
1. Since LG was created with [adaptive dialogs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-adaptive-dialog-introduction) in mind, you might consider using adaptive dialogs instead of these older dialogs.

**Comment by v-kydela** [comment]
@roberi - Are you still working on this?

**Comment by roberi** [comment]
@v-kydela - Thank you for your excellent explanation. I now understand how it all works. I will try some of your suggestions. You can close this issue.
