### ISSUE TITLE
[MS Teams]-Post request to smba.trafficmanager.net/xxx/v3/conversations/xxxx/activities/xxx returns canceled status

### ISSUE THREAD

**Issue by SathishNeel** [microsoft/BotBuilder-Samples#2489]
bot Builder: 4.5.1 C#

step to reproduce 

1. install bot in teams channel and type a query.it returns response.
2. deploy code changes and ping bot with sample query.
3. bot returns error message.

how to handle smba.trafficmanager failure.

**Comment by a-b-r-o-w-n** [comment]
@clearab Can you help triage this?

**Comment by clearab** [comment]
I'm not quite sure what you mean, could you provide a code sample or more detailed information about what you're trying to accomplish? Are you starting from one of our code samples?

**Comment by SathishNeel** [comment]
@clearab , we used 46.teams-auth bot sample . we have been while in teams channel and after every deployment bot not responding to user query.but if they signout and signin , it starts working . As a bot team, we are facing difficulties to explain this process to each one of the users. Please provide your suggestion to handle better.

**Comment by SathishNeel** [comment]
@clearab Yes, its from bot( logout and sign-in) .our bot is supporting domain functionalities (more than 21 process areas) adoption of 150k users .we have test and live environment and this issue occurring on both environment and most of the user are facing same error as mentioned here. Also verified in application insight log and it shows only this dependency failure.

**Comment by clearab** [comment]
It sounds like you're trying to either continue a conversation using a conversationId that no longer exists, or maybe trying to use an expired user token. Can you debug and figure out what specifically is happening in your code when this error is thrown? Since it is happening once for each of your users, I'm guess there is something amiss in like your user or conversation state storage. @Jeffders  or @carlosscastro maybe you have some ideas?

**Comment by clearab** [comment]
I'm going to close this for now - please feel free to re-open if you have additional information to share.
