### ISSUE TITLE
Button actions are not working in slack channel.

### ISSUE THREAD

**Issue by Krishna-chinthireddy** [microsoft/BotBuilder-Samples#2553]
Hi,

i have followed [this documet](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs) created slack app and enabled the slack channel in azure bot service. published a bot which is created with buttons responses(i have referred  [this templetes](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore) and created bot with button responses

The images and Plain text responses are working. but i am facing problem in button actions.
![image](https://user-images.githubusercontent.com/49742373/85947171-b4d6cc00-b966-11ea-92f9-f420fc4fb419.png)

when i click on button i am not getting any response. so i have kept the ngrok please refer the following image of ngrok result.
![image](https://user-images.githubusercontent.com/49742373/85947196-c9b35f80-b966-11ea-9f39-e860969ef90f.png)

IDK why i am getting 404 not found when i am clicking on button.
please any one help me to resolve this issue.

**Comment by v-kydela** [comment]
Thank you for the report, @kittu610. You might be interested in the info from this Stack Overflow question: https://stackoverflow.com/questions/62440845/bot-framework-unable-to-receive-button-clicks-from-slack

> ## Why aren't hero cards working in Slack?
> 
> First I need to mention that hero cards only work with the Slack connector and not the Slack adapter. You seem to be using the connector so you should be fine.
> 
> I suspect your problem is related to how you've configured your bot's settings on the Slack side. There is a step in the [Bot Framework doc][1] that seems to be important if you want to get buttons to work. If you've followed the doc exactly and you still can't get buttons to work, it may be worthwhile to dig into the [Slack API documentation][2].

  [1]: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs#add-and-configure-interactive-messages-optional
  [2]: https://api.slack.com/interactivity

I can tell you that the reason you're getting 404's in ngrok is because your bot endpoint isn't set up to respond to OPTIONS requests. This is a pretty normal thing to see in ngrok, and it doesn't indicate a problem since your bot can function just fine without responding to OPTIONS requests.

Since you are posting in the samples repo, are you following a specific sample? And are you using the Slack adapter or the Slack connector?

**Comment by kittu610** [comment]
Hi @v-kydela.

i am a echo bot template . just i have added a hero card has a response in that sample when user types any thing the bot is going to give a button has response when user clicks on that button user is going to get an image.

my error is that button responses have worked fine from past 20 days i have not done any changes but from past 3 days i am facing the issue with buttons. it is working fine in past some change have done in slack api.

please can you follow [this document](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs) and please deploy the sample bot project i have attached. and please can you help me to figure out how to resolve the button issue.
[sample bot.zip](https://github.com/microsoft/BotBuilder-Samples/files/4850194/sample.bot.zip)

**Comment by v-kydela** [comment]
@kittu610 - Thank you for the information, but I still need to know if you're using the Slack adapter or the Slack connector. You linked to the instructions for the Slack connector, but the appsettings.json in the sample you uploaded is set up to use the Slack adapter. The sample itself seems coded to work with both.

**Comment by kittu610** [comment]
Hi @v-kydela

i have used IBotFrameworkHttpAdapter.

**Comment by v-kydela** [comment]
@kittu610 - I tried creating a new Slack app and deploying the sample bot project like you said and it can't even display the card: 
![image](https://user-images.githubusercontent.com/41968495/86301291-5c980800-bbba-11ea-98d0-fd80ca72919f.png)

I also cannot run the project in debug mode. Can you?

**Comment by kittu610** [comment]
Hi @v-kydela,

Yes i have aware of Microsoft app id and password  i have deleted the creds before sharing you.

It seems like the packages are not loaded in the solution please can you re built all the packages using nuget package manager.

please can you keep debugger after rebuilding all the packages.

**Comment by v-kydela** [comment]
@kittu610 - Finally I am able to reproduce the problem and I'm now trying to determine the cause. Thank you for your patience.

**Comment by v-kydela** [comment]
All right, I've done some investigating and I believe the problem is in ABS. I have a working Slack app and a broken Slack app, and the working one was a ["classic"](https://api.slack.com/rtm#classic) Slack app that wanted me to migrate. Unfortunately the migration process says it breaks the RTM API:

![image](https://user-images.githubusercontent.com/41968495/86398113-f4006800-bc59-11ea-8bc5-abaa6280c22a.png)

From the [docs page](https://api.slack.com/rtm):

![image](https://user-images.githubusercontent.com/41968495/86398164-05497480-bc5a-11ea-91be-9bca56bbc949.png)

I determined that no other setting in the Slack app could be the culprit by meticulously making sure every other setting is the same between my two apps. I determined that the problem has nothing to do with my Azure resources because I switched which resource was connected to which app. The problem has to be with the way new Slack apps work. I did migrate my classic app and strangely enough it's still working, so there must be some internal behavior that's been carried over.

## To reproduce

1. Create a new Slack app following the instructions for connecting a bot to Slack in Azure
1. Run a bot that uses card actions
1. Observe that while normal messages work, clicked actions never reach the bot's endpoint

I will see if this can be fixed internally since it seems to be urgent.

**Comment by kittu610** [comment]
Hi @v-kydela 

Has followed i have created classic slack application but it has asked to update the scopes so i have updated the scopes and created the classic application but the issue is still persisting. still the buttons are not working.

please any more suggestions.

**Comment by v-kydela** [comment]
@kittu610 - Updating the scopes would be converting the classic Slack app to a new Slack app I think, which would defeat the purpose of creating a classic Slack app. In any case, did you try my other suggestion?

**Comment by kittu610** [comment]
Hi @v-kydela 

Sorry for the late reply.

i have tried with out updating the scopes in  classic app the result is same.  when i config the basic details of slack in azure i am facing this issue.
please find the below image.
![image](https://user-images.githubusercontent.com/49742373/86531952-76e82380-bee3-11ea-9b19-ced5f3055490.png)

i have created a bot using slack adapter. but i am not getting the logic how to send cards with out using bot framework rich cards?

Please can you share me the Sample code how it can be achieved.

**Comment by kittu610** [comment]
> All right, I've done some investigating and I believe the problem is in ABS. I have a working Slack app and a broken Slack app, and the working one was a ["classic"](https://api.slack.com/rtm#classic) Slack app that wanted me to migrate. Unfortunately the migration process says it breaks the RTM API:
> 
> ![image](https://user-images.githubusercontent.com/41968495/86398113-f4006800-bc59-11ea-8bc5-abaa6280c22a.png)
> 
> From the [docs page](https://api.slack.com/rtm):
> 
> ![image](https://user-images.githubusercontent.com/41968495/86398164-05497480-bc5a-11ea-91be-9bca56bbc949.png)
> 
> I determined that no other setting in the Slack app could be the culprit by meticulously making sure every other setting is the same between my two apps. I determined that the problem has nothing to do with my Azure resources because I switched which resource was connected to which app. The problem has to be with the way new Slack apps work. I did migrate my classic app and strangely enough it's still working, so there must be some internal behavior that's been carried over.
> 
> ## To reproduce
> 1. Create a new Slack app following the instructions for connecting a bot to Slack in Azure
> 2. Run a bot that uses card actions
> 3. Observe that while normal messages work, clicked actions never reach the bot's endpoint
> 
> I will see if this can be fixed internally since it seems to be urgent. In the meantime, you can try to mitigate the issue by creating a classic app or by using the Slack adapter. Note that you can't use Bot Framework card actions with the Slack adapter so you'll have to build blocks directly.

 Hi @v-kydela 

This is very important for us to deliver chat bot  for one of the customer. 
Please let us know if bot framework engineering team is working on the issue/feature and share those details with us for tracking

**Comment by v-kydela** [comment]
@kittu610 - The [Slack adapter sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/60.slack-adapter/Bots/EchoBot.cs#L65-L80) shows you how to use Block Kit with the Bot Framework

**Comment by youyu16** [comment]
@kittu610 The 404 is normal because your bot is not handling the OPTIONS call, this is not the issue and will not affect your bot flow.
As far as I know ABS has an issue which is using one of the slack API deprecated for newly created slack app from 6/10/2020. 
I'm start fixing this problem but currently not clear when it will be deployed.

**Comment by youyu16** [comment]
@kittu610 Slack is guiding us using their auth v2 by default and we have other customer report to using v2. The ABS is migrate to using auth v2 by default but v1 auth is still working for the old bot.
If you want still want to use the V1 you need to make the auth and "add to slack" link on your own. 
the example is here 
https://slack.com/oauth/authorize?scope=bot&client_id=your_client_id&redirect_uri=https://slack.botframework.com/Home/auth&state=your_bot_id

**Comment by srinutamada** [comment]
> @kittu610 Slack is guiding us using their auth v2 by default and we have other customer report to use v2. The ABS is migrate to use auth v2 by default but v1 auth is still working for the old bot.
> If you want still want to use the V1 you need to make the auth and "add to slack" link on your own.
> the example is below:
> https://slack.com/oauth/authorize?scope=bot&client_id=your_client_id&redirect_uri=https://slack.botframework.com/Home/auth&state=your_bot_id

Thanks for update, How to many if the same chat bot is working with different channels? we can't create chat bot for each channel right? If I make changes to OAuth to fix Slack issue, other channels will fail. And I can't create bot for each channel and will become complex in code maintenance.

If the issue can be fixed to work with default auth itself will be much appreciated.

**Comment by youyu16** [comment]
@srinutamada The PR is on its way, but need time to get it work.

**Comment by kittu610** [comment]
This following documentation has updated. but in document it mentioned that to add a bot user but i unable to find bot user field in slack application creation.
please find the below attached image. The popup has came when i clicked on where's bot user field on left side.
Screenshot (18)

i have searched in App home page also but unable to find it
Screenshot (20)

**Comment by v-kydela** [comment]
@kittu610 - In a classic app, I see the option to add a legacy bot user. Are you not seeing that in a classic app?

![image](https://user-images.githubusercontent.com/41968495/87065265-aa69cd00-c1c5-11ea-98d9-4defafed46dc.png)

**Comment by kittu610** [comment]
Hi @v-kydela 

Add legacy bot user option is there in classic slack application.

but in this updated [document](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs) they have mentioned to create an application using this [Url](https://api.slack.com/apps)
so i cannot find bot user  in that site.

**Comment by srinutamada** [comment]
> @kittu610 - In a classic app, I see the option to add a legacy bot user. Are you not seeing that in a classic app?
> 
> ![image](https://user-images.githubusercontent.com/41968495/87065265-aa69cd00-c1c5-11ea-98d9-4defafed46dc.png)

@v-kydela, Is there update on resolution? We need this issue to be resolve as soon as possible. So, please let us know target completion date?

**Comment by v-kydela** [comment]
@srinutamada - I'm sorry, but you'll need to ask @youyu16 if there is a target completion date. I can only provide support for the two workarounds I mentioned.

**Comment by youyu16** [comment]
@srinutamada The button's issue targeting to be fixed in later this week or next week.
but I think you are encounter other issues depend on your comments. Can you describe the auth issue you are facing? 
And you are talking about the "channel", you mean the channel in Botframework or the Slack's channel.

**Comment by kittu610** [comment]
> @srinutamada The button's issue targeting to be fixed in later this week or next week.
> but I think you are encounter other issues depend on your comments. Can you describe the auth issue you are facing?
> And you are talking about the "channel", you mean the channel in Botframework or the Slack's channel.

HI @youyu16 

The problem is out bot will run in all channels with the endpoint URL( URL/api/messages) because we have used only one controller.
if we add one more adapter called slack adapter we need to change the endpoint URL to (URL/api/slack)

so if we change the endpoint URL it is going to effect other channels

**Comment by youyu16** [comment]
@kittu610 Button actions should working now, please confirm.
![image](https://user-images.githubusercontent.com/17819112/87753230-bba18200-c834-11ea-9d15-7d12970f411a.png)

**Comment by kittu610** [comment]
Hi @youyu16 

I can confirm that button actions are working

**Comment by srinutamada** [comment]
> @kittu610 Button actions should working now, please confirm.
> ![image](https://user-images.githubusercontent.com/17819112/87753230-bba18200-c834-11ea-9d15-7d12970f411a.png)

@youyu16 Thank you very much for support. Much appreciated.

**Comment by Krishna-chinthireddy** [comment]
HI Team,

i was facing the issue related to this thread again now but somewhat differ 

Issue Description:-
if my bot has a response with single button it is working has expected but i am facing issue when the bot response has multiple buttons.

**Comment by congysu** [comment]
@v-kydela @youyu16 can you please take a look at this one?  Thanks.

**Comment by v-kydela** [comment]
@Krishna-chinthireddy - I don't think it's appropriate to reopen this issue because it sounds like you're facing a new issue. If you believe this is a Slack adapter but then you can raise the bug in the [.NET](https://github.com/microsoft/botbuilder-dotnet/issues) repo, if you believe this is a Slack connector bug then you can raise the bug in the [services](https://github.com/microsoft/BotFramework-Services/issues) repo, and if you believe this is a Slack bug then you should provide feedback to Slack. If you don't think this is a bug at all and you'd just like to know how to resolve your problem, you should ask a question on Stack Overflow. In any case, you'll need to provide a full explanation of your problem including links, screenshots, expected behavior, and actual behavior.
