### ISSUE TITLE
Add iFrame based Task Module samples for remaining languages

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotBuilder-Samples#2574]
On the back of the .NET sample https://github.com/microsoft/BotBuilder-Samples/pull/2546 - add this sample to the other languages.

- [ ] Python (https://github.com/microsoft/BotBuilder-Samples/tree/trboehre/teamstasks)
- [ ] JS
- [x] Java

**Comment by troykirin** [comment]
Working on a python project utilizing 54.teams-task-module. When clicking the button for "Custom Form" or "YouTube" given the sample, I'm getting the following bug (see images). I'm deploying it via ngrok and adding various "validDomains" to the manifest using "App Studio" inside a Teams Sandbox. Due to this still being an open issue, has this been been resolved?

![image](https://user-images.githubusercontent.com/11987882/100813729-cf6d0f80-33f4-11eb-8303-66a2b3c6cfd8.png)

![image](https://user-images.githubusercontent.com/11987882/100813772-ef9cce80-33f4-11eb-98e6-d2181fa6f1b5.png)

@tracyboehrer @garypretty

**Comment by troykirin** [comment]
I was able to resolve this by enabling HTTPS only in the App Service.

![image](https://user-images.githubusercontent.com/11987882/101928434-6de23900-3b8a-11eb-8243-1a8f26ada5c9.png)

**Comment by karolh2000** [comment]
@troykirin  Hi Troy,  Could you provide more info about how you fixed this problem? Basically, I struggle with the same problem and am not able to use Task Modules because of it. What resource is shown on the screen shot?
