### ISSUE TITLE
Test for and mitigate "InvalidTemplate" errors in Samples

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/BotBuilder-Samples#2631]
Beginning June 17th, virtually all ARM templates of the "new resource group" variety used in bot deployments have generated "InvalidTemplate - Deployment template validation failed" errors. They are typically named "template-with-new-rg.json". 

The templates in the BotBuilder-Samples repo should be tested for that error. If they error, they present a pitfall for users attempting to deploy bots to Azure. Monica Rivera is currently pursuing the Azure DevOps team for a solution.

One way to mitigate this problem is to remove the templates from the repo until the problem is solved. Users would still have the "existing resource group" variety of templates to use for bot deployments. Those are typically named "template-with-preexisting-rg.json".

**Comment by BruceHaley** [comment]
This issue: [https://github.com/microsoft/BotFramework-FunctionalTests/pull/121/files](https://github.com/microsoft/BotFramework-FunctionalTests/pull/121/files) -- shows a template fix that could likely be used here.

**Comment by EricDahlvang** [comment]
@dmvtech has verified dotnet sample 6 'template-with-new-rg.json' is broken, and the fix from functional tests fixes it.

**Comment by mrivera-ms** [comment]
**Background information:**

This error happens in the templates that use nested deployments, where the dependency is evaluated in the context of the outer template by default.  [More info here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#expression-evaluation-scope-in-nested-templates) .

To change this behavior, a property `"expressionEvaluationOptions": { "scope": "inner" }`, must be added.

**Steps needed:**

1. Verify what samples fail to deploy with an error similar to: 
`2020-07-22T02:17:06.3141288Z InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/***' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.`
2. For each failed deployment, find the template being used and apply the fix found here: [BoFramework-FunctionalTests/pull/121](https://github.com/microsoft/BotFramework-FunctionalTests/pull/121).

At a high level, the fix does the following:
- Adds the necessary property to set the scope to "inner", to the templates that use inner deployments.
- Adds new parameters to the inner template as setting the scope to "inner" prevents the inner template from seeing the outer parameters and variables.

**Comment by v-kydela** [comment]
@BruceHaley 
@mrivera-ms 

Has anyone been able to determine why this started happening on June 17th? Is it because of a specific change in Azure?

**Comment by mrivera-ms** [comment]
> @BruceHaley Bruce Haley (Harvey Nash) Vendor
> @mrivera-ms Monica Rivera FTE
> 
> Has anyone been able to determine why this started happening on June 17th? Is it because of a specific change in Azure?

We don't have any information about the change that triggered this issue. None of the teams we have talked to has acknowledged any changes.

**Comment by v-kydela** [comment]
Here is an update on my progress. I've reproduced the error and I've reproduced the fix. I'm currently gathering data to determine the fastest way to fix the problem for all the ARM templates in all the samples in all the languages.

I have determined that the ARM templates are not specific to the samples they're bundled with. The preexisting RG templates just provision an app service plan, an app service, and a bot channels registration. The new RG templates do the same but after creating a new resource group. The reason the problem doesn't occur with the preexisting RG templates is because they don't use a nested template. The new RG templates use a nested template because the main template has a deployment as a resource, and that deployment resource waits for the creation of the resource group to finish.

The templates don't provision cognitive services or storage resources, they don't access the bot code that they're bundled with. The developer has to actually publish the code in a subsequent step. This means the ARM templates are so loosely coupled with the samples they're bundled with that the AZ CLI command to deploy them can be run from anywhere. Because of this, I am now in the process of centralizing the ARM templates by reducing the amount of duplicates. This will make testing and fixing go faster.

Here are the main differences that I've discovered between ARM templates so far:

1. The templates for the Python samples are meant for Linux and so they're different from the Node and C# templates
1. Some of the templates enable WebSockets in the app service, but since there's no compelling reason not to do this I plan to eliminate this difference by having all templates do this
1. The templates for the Teams samples add the Teams channel. I'm considering eliminating this difference as well by having them all add the Teams channel

**Comment by mrivera-ms** [comment]
@v-kydela This is great progress, Kyle. Can you elaborate on the idea of a centralized location?

**Comment by v-kydela** [comment]
@mrivera-ms - Yes, I'm going to delete most of the DeploymentTemplates folders so it's clear that they don't represent their own unique templates. Right now the plan is to have a DeploymentTemplates folder in the root folder for each language, and only have a DeploymentTemplates folder in individual samples if I find unique ones. I'm also considering going up a level further and having a shared folder for Node and C# since their templates seem to be the same.

**Comment by v-kydela** [comment]
I've eliminated over 200 template files and now there are about 100 remaining for me to check (50 pairs, since I'm checking both the new-rg and preexisting-rg templates). I've made it so that they all add the Teams channel and all the C# templates enable WebSockets. I'm unsure why none of the templates in the JS samples enabled WebSockets but they didn't so I just left them that way. There seems to be some randomness when it comes to which templates are in which samples so I suspect a lot of the discrepancies I'm seeing are just mistakes. I could try to track down the people who designed and wrote these templates but even if I did that I'm doubtful that I'd get meaningful explanations for the discrepancies.

I'm almost done with the samples folder and I'll move on to the experimental, generators, and MigrationV3V4 folders after that. Here are some more differences I've encountered:

4. The C# skills samples had an extra parameter in the preexisting-rg template called existingAppServicePlanResourceGroup. I couldn't discern any reason this parameter should be specific to C# or to skills or to preexisting-rg templates, and the parameter isn't mentioned in the deployment doc so customers can't really use it anyway. I decided to just get rid of it for consistency.
5. Most of the Python sample templates use gunicorn in the appCommandLine property of their site config resources, so I decided to just have all of them use it.

**Comment by mrivera-ms** [comment]
@v-kydela , thanks for the analysis. I ask you to wait before making these changes until we can confirm this is approved by the team.

**Comment by v-kydela** [comment]
@mrivera-ms - If the team is going to make a decision about the best way to fix this then there's something else I want to bring up as a possibility.

The readmes in the samples all explain how to deploy by simply linking to this doc: https://aka.ms/azuredeployment

I'm written before about how there are many ways to deploy a bot, and deployment is an ambiguous term anyway. I think it's unfortunate that the only route we explain is to use AZ CLI. It's fine to present that as an option so long as the Azure portal route isn't omitted. It's my opinion that the primary route should be the Azure portal because it's the easiest, most intuitive, least error-prone, and gives the most understanding about what's going on. That means if we only explain one route, it should be the Azure portal.

Since the templates just create the resource group, the bot channels registration, the app service plan, and the app service, they don't do anything the Web App Bot resource creation doesn't already do. On top of that, creating the resource in the Azure portal also makes an AAD app registration for you so you don't have to worry about that step.

Even considering that I'm already partially done with fixing the templates, I suspect updating the docs to explain how to provision resources on the Azure portal instead of using the templates may be the fastest solution to the issue.

**Comment by v-kydela** [comment]
@mrivera-ms - Is this issue still on hold? Should it remain open?

**Comment by mrivera-ms** [comment]
@v-kydela , let's go ahead and fix the templates and not make any changes to the folder structure. The team has concerns about how that change affects the customers, so we will not make that change at this point. Thank you.

**Comment by v-kydela** [comment]
@mrivera-ms - Well it may take a bit longer this way but I'll do my best. I'm working on a way to automate the process so I can test and fix everything as quickly as possible.

**Comment by BruceHaley** [comment]
@v-kydela, while you are thinking about how to normalize and simplify ARM templates, consider that offering both a "preexisting rg" template and a "new rg" template is redundant, since deploying a bot can be done either way. It would simplify matters to delete one of them everywhere and just offer the other. Southworks put both in originally, and no one questioned it at the time. This PR shows yaml code that allows either template to be used: https://github.com/microsoft/botbuilder-dotnet/pull/4441/files

**Comment by v-kydela** [comment]
Here is the tool I made to fix the templates: https://github.com/v-kydela/TemplateFixer

Most of the templates have already been fixed successfully using Bruce's fix, so I expect to be making a PR tomorrow. I'm noticing that there's a LinuxDotNet folder in samples 2 and 13 which contains a new-rg template that doesn't match the parameters of the other templates and therefore can't be used with the instructions in the docs. I suspect those templates were named incorrectly, and I'm not sure whether fixing that is within the scope of this issue.
