### ISSUE TITLE
14.nlp-with-dispatch: Weather.json cannot be imported to LUIS

### ISSUE THREAD

**Issue by wendingp** [microsoft/BotBuilder-Samples#2643]
When I import Weather.json, I got imported failed: 

> BadArgument: Invalid luis schema version. Failed to parse application json.

**Comment by anusharavindrar** [comment]
@wendingp, I could repro the issue. The problem is due to the missing **luis_schema_version**  in the Weather.json file.  The workaround is to add **"luis_schema_version": "3.2.0"** in the Weather.json file. Please try adding this line in the Weather.json and save it and try importing it again, it will be successfully imported without any errors.

![image](https://user-images.githubusercontent.com/48731427/89450183-05340d00-d70f-11ea-9de1-bf13033314b3.png)

I will get a PR out to have this fixed and reflect correctly in the samples.
