### ISSUE TITLE
Customise header and control options in Teams - Task Module

### ISSUE THREAD

**Issue by ravikant15796** [microsoft/BotBuilder-Samples#2656]
**Sample information**

teams-task-module
Node JS
Bot Framework 

**Is your feature request related to a problem? Please describe.**
1. There should be options in task module to change position of header icon and text. currently by default task module showing these in top left. 

2. I want show hand icon on hovering over play/pause icon, Progress bar, Mute/ unmute, Full Screen and download while playing videos in task module but there is no options for this.

**Describe the solution you'd like**

Apart from title, height, width, url, card, fallbackUrl, completionBotId more control options should be present in TaskInfo object for controlling popup/iframe

reference url :- https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules

**Additional context**
screenshots about the feature requested here.

[enhanc
![taskmodule](https://user-images.githubusercontent.com/10558023/89631546-8aa9ef80-d8be-11ea-8c55-0c387d2717cd.jpg)
ement]

**Comment by daveta** [comment]
Hi @clearab : Can you take a look?

**Comment by clearab** [comment]
Hi - thank you very much for the feedback. Microsoft Teams accepts feature requests through the User Voice platform which you can find here: https://microsoftteams.uservoice.com/forums/555103-public/filters/new. If you'd like to reach out to the Teams group directly to speak with them, you can do so in one of the methods outlined here: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback.

I know this functionality has been requested in the past - I'll flag this Issue for them so that they know the request was made here as well.

Closing this as there is no action possible to fulfill this request from the Bot Framework SDK team.

**Comment by robin-liao** [comment]
For the Ask#2, it looks like the media player is on a webpage. So it should have full control of CSS style including cursor pointer.
