### ISSUE TITLE
Bot is bit confused to capture the user's intention

### ISSUE THREAD

**Issue by kittu610** [microsoft/BotBuilder-Samples#2662]
Hi,

I have enabled email channel in azure and deployed  bot in azure.

the bot is bit confused to capture the users intention

For example:- If user sent a mail to bot like
![image](https://user-images.githubusercontent.com/49742373/89777770-f774f200-db29-11ea-9ad4-ff1709452cb5.png)

The bot need to capture "what can you do" and need to send a reply but bot is capturing 
"HI Bot.\r\n\r\n\r\n\r\nWhat can you do\r\n\r\n\r\n\r\nThanks and regards,\r\n\r\nKrishna." 

IF user sends
![image](https://user-images.githubusercontent.com/49742373/89778255-ce089600-db2a-11ea-9d01-8fa869f88815.png)

The bot need to capture "hi" and need to reply with specific responce
but the bot is capturing "hi\r\n\r\n\r\n\r\nThanks and regards,\r\n\r\nKrishna.".

is there any way to understand the users intention.

if user mails only greeting the bot has to welcome the user with welcome message, if user mails some question  with greetings the bot has to capture specific users intention.

Because every user has different standard signatures and formats in there mails.
please suggest me the best approach.

**Comment by Zerryth** [comment]
@kittu610 , you must simply add your own  custom business logic to parse the data that you are sending over to LUIS. 
Additionally LUIS does provide NLP, however on its own it is not the right tool to use in an email conversation.

___

* LUIS is designed to parse intentions from a succinct utterance--it is not a tool for document summarization, and can't parse from a large block of text--especially since large blocks of texts most likely point to multiple intents throughout.
    * This text-limit makes using LUIS particularly difficult in email conversations, where the user could potentially respond with large swaths of paragraphs
* If you take a look at the [Extract data from utterance text with intents and entities](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-data-extraction?tabs=V2) article, you can find the prediction endpoints where you can send your test queries in that LUIS can actually predict an intent from, and build your custom bot logic try to winnow down the utterance you're sending to LUIS from your bot.
* Additionally, you could try looking into https://github.com/microsoft/nlp-recipes for a different tool that is specifically designed to handle document summarization, and maybe feeding the summary into LUIS to parse the intent--or perhaps even cut LUIS out of your email bot altogether.

___

Closing this, as the Bot Framework repos are intended to report bugs or request feature requests. 
For further how-to questions, please detail what you have tried to resolve the issue (adding custom logic, help with nlp-recipes, LUIS, etc.) on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework) and leverage the help of the community.

**Comment by srinutamada** [comment]
Hi @Zerryth 
When I use outlook as channel, is there any way to ignore end user's signature or disclaimer if email content has? As per my understanding, outlook channel supposed to differentiate user's content from signature & disclaimers. Let me know if its not possible and we have to write our own logic for the same.

**Comment by Zerryth** [comment]
@srinutamada with certainty the Bot Framework SDK and Azure Bot Service in the Azure Portal *do not* have an already built-in API that you could call to ignore greeting/signature, unfortunately.

Continuing the conversation on the [StackOverflow post ](https://stackoverflow.com/questions/63351769/bot-is-bit-confused-to-capture-the-users-intention)that kittu610 opened regarding this topic, as this is beyond the scope of Bot Framework itself, and more in the realm of Microsoft Graph API or Outlook API. Including some resources as well that you could start to search through to find some answers.


You could try digging further by looking into the Graph API or Outlook APIs directly:
https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0

However upon a precursory glance, I don't see anything that would indicate the
