### ISSUE TITLE
Orchestrator: QnAMaker Multiturn

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotBuilder-Samples#2928]
Does Orchestrator supports QnAMaker multiturn

**Comment by jwiley84** [comment]
Can you clarify what you mean by 'support'? Can you clarify more about your scenario? Because Orchestrator is a successor to dispatch where you can use Orchestrator instead of the current dispatch solution to arbitrate across your LUIS and QnA Maker applications. There should be no difference between Orchestrator handing a simple QnA, and handling a multi-turn QnA.

**Comment by KoradaRajesh** [comment]
Is it possible to get multiturn context values from qna maker using Orchestrator

**Comment by tsuwandy** [comment]
@KoradaRajesh, what would be the query given to Orchestrator and your expected Orchestrator response in the multiturn scenario?  I suppose this is in Dispatch scenario (QnA kb + LUIS app) or a single QnA kb?

**Comment by hcyang** [comment]
Hi @KoradaRajesh, can you be more specific on what you would like Orchestrator to support QnA Multiturn? For example, can you give us a QnA MultiTurn example and what info (fields, JSON attribute) in it would you like to be used by Orchestrator for training a model?

**Comment by tonyanziano** [comment]
Closing as stale. Please feel free to re-open.
