### ISSUE TITLE
81.skills-skilldialog doesn't handle OPTIONS requests

### ISSUE THREAD

**Issue by wonboyn** [microsoft/BotBuilder-Samples#3004]
## Sample information
1. Sample type: \samples\ 
2. Sample language: python
3. Sample name: 81.skills-skilldialog

## Describe the bug
The sample sets up an aiohttp web app with routes for GET/POST to /api/messages
But it does not handle OPTIONS requests. Consequently when you try to test using the web chat blade in Azure portal or setup a Teams channel you get an error when it attempts an OPTIONS request to /api/messages

## To Reproduce
1. Run the root & skill bot apps
2. Start ngrok routing for port 3978
3. Update the Azure Bot Service Messaging Endpoint configuration to point to the ngrok address with the suffix /api/messages (eg https://38e6f60db143.ngrok.io/api/messages)
4. See error in ngrok console output: "500 Internal Server Error"

## Expected behavior
Options requests from Azure Bot Service handled correctly

**Comment by v-kydela** [comment]
Thank you for the report, @wonboyn. No Bot Framework sample has ever handled OPTIONS requests, and the Bot Framework contains no functionality for doing so. Do you have an expectation for how you'd like this to be handled globally?

If you'd like the SDK to include OPTIONS functionality then this should be in the SDK repo: https://github.com/microsoft/botframework-sdk

If you'd just like the samples to change then this issue should remain in the samples repo but it should be reworded so that it doesn't only apply to one sample.

Note that my recommendation is to ignore this issue. Failed OPTIONS requests will not negatively affect your bot, and it's common for web apps to ignore OPTIONS requests.
