### ISSUE TITLE
Support DynamicList templates as part of standard schema

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotBuilder-Samples#3132]
LUIS recognizers support the ability to define dynamic lists that are passed in at runtime.  To do this your LUIS model needs to have a place holder entity which is statically populated at training time and dynamically populated at runtime.  The LUIS recognizer would look like:
"recognizer": {
            "$kind": "Microsoft.LuisRecognizer",
            "applicationId": "=settings.luis.DynamicLists_test_en_us_lu.appId",
            "endpoint": "=settings.luis.endpoint",
            "endpointKey": "=settings.luis.endpointKey",
            "dynamicLists": "=[dialog.PersonValue, dialog.RoomNumberValue]"
}
Then we would have an action template to fill in the runtime definition of dialog.person and hang that off of beginDialog.  It would have a SetProperty(dialog.person, LISTSTRUCTURE).  The default definition would be the same one generated for the training time, but this would give people a place to dynamically calculate the list to pass in.

Inside of BeginDialog is an action which looks like:
```
{$kind: Microsoft.SetProperty, property: "dialog.PersonValue", value: "{
                    "entity": "PersonValue",
                    "list": [
                        {
                            "canonicalForm": "Chris McConnell",
                            "synonyms": [
                                     "Chris",
                                     "McConnell"
                            ]
                        },
                        {
                            "canonicalForm": "Zongyang",
                            "synonyms": [
                            ]
                        }
                    ]
                },
```

To actually make this dynamic someone could call the graph API and compute this structure to set in memory that would then be passed into the LUIS recognizers.

This schema should be of type string with $examples that look like enum $examples.  

Person: {$ref: "dynamiclist.schema", $examples: {"": {PersonValue: { "Christopher McConnell": ["Chris", "Christopher"]}}}.  Then from this you generate a PersonValue LUIS list with the $examples and you use the same name when passing in a dynamic list.

You can view this as an open-ended enum (which is why its type is just string) where you can statically define training data and at runtime supply dynamically defined definitions.

1) Define dynamiclist.schema.   Type is string and may be able to reuse enum templates.
2) Extend recognizer template to add dynamiclists and the list is empty if there are no dynamic templates.
3) For each dynamic property add a SetProperty action to the begin dialog for setting the dynamic list in memory.

Examples from tests: `botbuilder-dotnet-main\tests\Microsoft.Bot.Builder.AI.LUIS.Tests\tests\LuisAdaptiveRecognizerTests\DynamicLists.test.dialog`

**Comment by coldplaying42** [comment]
I go through all the codes related to dynamiclist in botbuilder-dotnet. I think the logic as follows:

If options.dynamiclist is not null, it will be added in the query content. The query content with uri will be sent to LUIS server (implemented in the function of RecognizeInternalAsync). Based on my understanding, the data in the dynamiclist will be trained when LUIS server receiving it. When LUIS trains data in dynamiclist, does it need the corresponding lu file with example utterances? In that case, why do we need to set property in begin dialog, since dynamiclist already includes all information needed?

I think the usage of dynamiclist.schema is similar to that of form-global.en-us.data, we have some templates and use functions like substitutions to replace some parameters with $example of PropertyValue. Then the dynamiclist of the PropertyValue is generated. Is my understanding correct?
