### ISSUE TITLE
.env uses incorrect key (current: MicrosoftAppId but it should be MicrosoftAppID)

### ISSUE THREAD

**Issue by lucaswillering** [microsoft/BotBuilder-Samples#3316]
In the /samples/javascript_nodejs/07.using-adaptive-cards project, the .env file contains the key `MicrosoftAppId`. However, index.js looks for `process.env.MicrosoftAppID`. This can result in the following error when trying to run the bot: BotFrameworkAdapter.processActivity(): 401 ERROR Error: Unauthorized. Invalid AppId passed on token [TOKEN]

https://github.com/microsoft/BotBuilder-Samples/blob/d360da100671aca9653c9ceb6b9b5000aaa0a7fd/samples/javascript_nodejs/07.using-adaptive-cards/.env#L1

**Comment by v-kydela** [comment]
Thank you for the report, @lucaswillering 

You've identified a discrepancy between an identifier in two files, and you concluded that .env is the file that needs to be corrected when in fact the problem was in index.js. `MicrosoftAppId` is the correct convention used in the Bot Framework, and you can verify this by looking at other samples. I've submitted a pull request to fix the problem.
