### ISSUE TITLE
Slack adapter not working as expected

### ISSUE THREAD

**Issue by mmiele** [microsoft/BotBuilder-Samples#3463]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore 
3. Sample name: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/60.slack-adapter
4. Related documentation: [Create a Slack application using the Slack adapter](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0#create-a-slack-application-using-the-slack-adapter).

## Describe the bug
The bot does not echo back the received messages. 

## To Reproduce
1.	Run the sample on local machine
2.	Activate ngrook 
3.	Configure Slack app with proper redirect and request URL (end point https://yyyy.ngrok.io/api/slack).
4.	Send user messages from Slack to the bot via the related Slack app. 
5.	Messages are received by the ngrook end point as shown in the ngrook terminal window (200 OK). This is also shown in the debug trace in Visual Studio,

## Expected behavior
The bot should echo back the received messages.

## Additional context
Based on the debugging trace, I verified that Slack sends messages to the bot adapter. But I the bot does not echo back the messages received. Is it possible that the Slack API has changed but the changes is not reflected in the SDK?

**Comment by ceciliaavila** [comment]
Hi @mmiele, @mrivera-ms, new Slack Apps need to have the `chat:write` scope enabled in order to post messages. See documentation [here](https://api.slack.com/methods/chat.postMessage).
After enabling this scope, the bot sample should start echoing back the messages.
![image](https://user-images.githubusercontent.com/44245136/144285324-f01c3a6e-9093-455c-b623-155f99bb0be1.png)
We'll update the documentation to include this new requirement.
