### ISSUE TITLE
46.teams-auth sample got 401 unauthorized when used the latest Azure Bot service to register a MS Teams bot. 

### ISSUE THREAD

**Issue by frankchen76** [microsoft/BotBuilder-Samples#3667]
regarding 46.teams-auth sample, when I used "Azure Service" to register the MS Team Bot with an existing Azure AD Application created separately, I got 401 unauthorized from ngrok windows after I delivered it to MS Teams. previously, I used "Bot Channel registration" without problems. since "Azure Bot" replaced "Bot Channel Registration" in Azure, can anyone share a latest instruction how to register a MS Teams bot via "Azure Bot"
a side question, when used "Azure Bot", there are "User-assigned managed Id", "Single tenant" and "Multi tenant" options, Can anyone share a doc what exact meaning are for those options?

**Comment by anishprasad01** [comment]
The instructions in the [teams-auth README](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth) are slightly out of date, but still correct. The only difference is that you create an `Azure Bot` resource instead of a `Bot Channels Registration` resource. Other than that, the steps are still the same.

A 401 error means that the application cannot identify the caller, and is therefore blocking it from accessing the resource. If you're getting this error, double check that everything is correct. 
- Did you make sure to add `/api/messages` in the Azure Bot configuration? If you're trying to access the wrong endpoint, you might get this.
- The instructions tell you to point ngrok to port `3978`, but is your bot actually running on that port? You might need to adjust where you point ngrok to.
- Did you add your credentials in the appropriate places in the bot's code?
- Did you enable the Teams channel in your Azure Bot?

As far as the three options you mentioned go, they refer to different ways to manage access to your bot.
- User-assigned managed identities are an Azure concept that allows you to create one identity and share it across multiple Azure resources, freeing you from needing to make a new token for each Azure resource. Here are some docs on [Azure managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) and [Bot app registrations](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned).
- Single-tenant means the bot will only be accessible to users with accounts in the assigned organizational group. These groups are called *tenants* by Azure Active Directory.
- Multi-tenant means the bot will be accessible more widely, to people who may not be part of your organizational group.

Usually you'd choose user-assigned managed identities, but there may be some scenarios in which you might need to [manually manage registration](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned#manual-app-registration). Here's some documentation on [AAD tenants](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/intro-azure-active-directory) as well for your convenience.

You can also use single or multi-tenant to run the teams-auth sample, I don't think it will matter all that much.

**Comment by frankchen76** [comment]
@anishprasad01, thank you so much for quick response and explanation. It looks like the 401 issue went away after I recreate my Azure AD applications for bot and idp. However I got another issue that I always got "Unable to reach app, Please try again" after I clicked "Sign in" button and completed the authentication at the first time. My ngrok screen showed "404 Not Found" and I was able to see the MS Teams send a post message with authentication code in "value/state". After I saw the error message, I typed anything else and received "Login was not successful please try again.". At this time, if I typed something again to trigger the authentication, everything works fine. I tried many times, it's always success at the second time. 
![image](https://user-images.githubusercontent.com/9618662/147616811-edddcc32-71ec-4f65-8567-b622b47a7565.png)

this is my ngrok screen:
![image](https://user-images.githubusercontent.com/9618662/147616853-bdfecabc-566f-4086-898f-510b65e02e82.png)

error message from vscode:
```
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: ProcessActivityAsync
info: Microsoft.BotBuilderSamples.DialogBot[0]
      Running dialog with signin/verifystate from an Invoke Activity.
Microsoft.BotBuilderSamples.DialogBot: Information: Running dialog with signin/verifystate from an Invoke Activity.
TeamsAuth Information: 0 : 'invoke' ==> activityReceived ==> OAuthPrompt
TeamsAuth Information: 0 : 'invoke' ==> activityReceived ==> MainDialog
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      GetTokenAsync ConnectionName: BotAuth01-Idp
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: GetTokenAsync ConnectionName: BotAuth01-Idp
info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET https://api.botframework.com/api/usertoken/GetToken?userId=29%3A1i5dZRwbIacd_YXU7IUTV1fGIim_P6HQDsdW3iI2XdkDaHYfuR-WbzMAVXN56yXrugXjgRtHmB9W5bFyYeJM2tg&connectionName=BotAuth01-Idp&channelId=msteams&code=114754
System.Net.Http.HttpClient.Default.LogicalHandler: Information: Start processing HTTP request GET https://api.botframework.com/api/usertoken/GetToken?userId=29%3A1i5dZRwbIacd_YXU7IUTV1fGIim_P6HQDsdW3iI2XdkDaHYfuR-WbzMAVXN56yXrugXjgRtHmB9W5bFyYeJM2tg&connectionName=BotAuth01-Idp&channelId=msteams&code=114754
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://api.botframework.com/api/usertoken/GetToken?userId=29%3A1i5dZRwbIacd_YXU7IUTV1fGIim_P6HQDsdW3iI2XdkDaHYfuR-WbzMAVXN56yXrugXjgRtHmB9W5bFyYeJM2tg&connectionName=BotAuth01-Idp&channelId=msteams&code=114754
System.Net.Http.HttpClient.Default.ClientHandler: Information: Sending HTTP request GET https://api.botframework.com/api/usertoken/GetToken?userId=29%3A1i5dZRwbIacd_YXU7IUTV1fGIim_P6HQDsdW3iI2XdkDaHYfuR-WbzMAVXN56yXrugXjgRtHmB9W5bFyYeJM2tg&connectionName=BotAuth01-Idp&channelId=msteams&code=114754
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response after 131.0109ms - NotFound
System.Net.Http.HttpClient.Default.ClientHandler: Information: Received HTTP response after 131.0109ms - NotFound
System.Net.Http.HttpClient.Default.LogicalHandler: Information: End processing HTTP request after 190.6132ms - NotFound
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 190.6132ms - NotFound
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      SendActivitiesAsync for 1 activities.
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: SendActivitiesAsync for 1 activities.
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: Sending activity.  ReplyToId: f:1b01bd61-619c-ce2f-248e-b62dd6d987fd
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      Sending activity.  ReplyToId: f:1b01bd61-619c-ce2f-248e-b62dd6d987fd
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      SendActivitiesAsync for 1 activities.
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: SendActivitiesAsync for 1 activities.
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      Sending activity.  ReplyToId: f:1b01bd61-619c-ce2f-248e-b62dd6d987fd
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: Sending activity.  ReplyToId: f:1b01bd61-619c-ce2f-248e-b62dd6d987fd
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Microsoft.BotBuilderSamples.BotController.PostAsync (TeamsAuth) in 285.2505ms
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action Microsoft.BotBuilderSamples.BotController.PostAsync (TeamsAuth) in 285.2505ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Microsoft.BotBuilderSamples.BotController.PostAsync (TeamsAuth)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'Microsoft.BotBuilderSamples.BotController.PostAsync (TeamsAuth)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 298.7115ms 404
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 298.7115ms 404
```

**Comment by timoleo23** [comment]
Hi, I got the same issue - UserAssignedMSI only works when the app is running on Azure - When running locally (using ngrok), you can't use managed identities (the app will receive the messages but wou't be able to reply back) - Can you try with the Single-Tenant or Multi-Tenant options?

**Comment by anishprasad01** [comment]
@frankchen76 

Please try out @timoleo23's idea in your bot and let me know what happens. Additionally, are you using the C# Teams auth sample as-is without modifications?

**Comment by frankchen76** [comment]
@timoleo23, thanks for your note. I registered Azure Bot using "MultiTenant" option, not UserAssignedMSI. please see below screenshot. I believe my local setup can receive the message without problems. The issue was I always got the error message at the first time. If I tried after failed, it worked fine. However, after I typed "logout", the first time will be failed, I have to try the second time, and then it works (see my screenshot above). 
![image](https://user-images.githubusercontent.com/9618662/147692267-5512969c-1693-481b-ace3-b2ae959a638c.png)

@anishprasad01, I cloned the original code without changing anything. the only thing I updated was the appsettings.json and manifest.json files to align Azure Bot registration. Thanks

**Comment by timoleo23** [comment]
Can you please check the following :
1. Is your app for user authentication registered as multi-tenant? If yes, can you change the tenantID in the OAuth connection of the bot to « common » instead of your tenant ID
2. Based on this previous issue, can you confirm that you have an app manifest deployed in Teams to chat to your bot (and do lot use the direct chat mode via the bot-ID)?  https://github.com/MicrosoftDocs/bot-docs/issues/1184

**Comment by anishprasad01** [comment]
@frankchen76 

Please double-check that second bullet point provided by the other commentor, as using an app package can sometimes resolve issues.

I will attempt a repro on my end and come back with an update.

**Comment by frankchen76** [comment]
@timoleo23, please see my comments below for your questions

1. the idp AAD App was created using "Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox" option. I updated Azure Bot connection to use "common", the problem still existed. previously, as I mentioned I can got token every other time. But after I changed to "common", I cannot get it worked. the below is the configuration and error message
![image](https://user-images.githubusercontent.com/9618662/147778199-1b2766a2-b632-4364-aebf-4ada33902f41.png)

2. Yes I deployed the manifest to the MS Teams. the issue was from MS Teams not direct connect. I tried it on Bot Emulator and there is no problem via Bot Emulator. 
Thanks

**Comment by anishprasad01** [comment]
I'm still in the process of investigating, and hope to have something in the near future.

**Comment by anishprasad01** [comment]
@frankchen76,

Can you confirm that your `apppsettings.json` file matches this [sample](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/46.teams-auth/appsettings.json)?

Specifically, ensure that `ConnectionName` and `UseSingleSignOn` are specified and set to the name and true, respectively. You don't need tenant id for a multi-tenant bot, but you can specify it anyway if you wish.

**Comment by frankchen76** [comment]
@anishprasad01, thanks for your note. I used the below app settings which should be same as what you provided: 
```JSON
    "MicrosoftAppType": "",
    "MicrosoftAppId": "XXX-bf010bfed165",
    "MicrosoftAppPassword": "XXXZ68",
    "ConnectionName": "BotAuth01-Idp",
    "UseSingleSignOn": false,
    "MicrosoftAppTenantId": "XXXXX-dce9"

```

**Comment by anishprasad01** [comment]
`UseSingleSignOn` should be set to true.

**Comment by anishprasad01** [comment]
There is always work being done on AAD, so that's certainly a possibility. As far as the use of `UseSingleSignOn` goes, in my testing I was unable to get AAD auth to work in Teams at all without using it and setting it to true. It might vary across different application configurations, but it's good to keep it in mind in the event that it is needed.

Since your issue appears resolved, I think we're ready to close this issue. Please feel free to comment and reopen or create a new issue as needed.
