### ISSUE TITLE
`GetAdaptiveCard()` from sample results in an error

### ISSUE THREAD

**Issue by slcwebguy** [microsoft/BotBuilder-Samples#3727]
## Sample information
1. Sample type: \samples\
2. Sample language: nodejs
3. Sample name: `50.teams-messaging-extensions-search`

## Describe the bug
Searching for `adaptive card` produces an error: `Unable to reach app. Please try again.`

## To Reproduce
1. Configure and run app according to instructions in the README
2. Zip and install the custom app (also according to the README instructions)
3. Bring up the app's search
4. Search for the following: `adaptive card`
5. See error

## Expected behavior
I think one of the following two corrections would be good. Either a) the search should display and function correctly or b) the `GetAdapterCard()` and related logic/functionality should be removed from the sample.

## Screenshot
<img width="380" alt="image" src="https://user-images.githubusercontent.com/26755361/162638020-ac6f2775-7c42-4238-a685-5c2e3fbb5717.png">

## Additional context
Applying the following patch, prevents the search from erroring. However, it exposes two new issues. After selecting the result: 1) its card appears only briefly in the compose area before disappearing and 2) after sending the now-blank compose message, the card is shown in the message stream but, sadly, it's shown in duplicate. These issues are captured in the screen recording which I've attached below the code patch.

### Patch
```
diff --git a/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js b/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js
index 823ff95d8..cb70029c7 100644
--- a/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js
+++ b/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js
@@ -55,6 +55,10 @@ class TeamsMessagingExtensionsSearchBot extends TeamsActivityHandler {
                 'Please select to get the card'
         );

+        AdaptiveCard.body = [{
+            type: 'TextBlock',
+            text: 'descrip',
+        }];
         const adaptive = CardFactory.adaptiveCard(AdaptiveCard);

         const attachment = { ...adaptive, preview };
```

### Screen recording (post patch)
https://user-images.githubusercontent.com/26755361/162638479-0d2641fd-9135-4c34-b752-83182460ff87.mp4

**Comment by stevkan** [comment]
@slcwebguy, can you tell me which version of Node you are running? And, just verifying that this is a current copy of the sample?

**Comment by slcwebguy** [comment]
@stevkan , the node version is `14.18.1` and, yes, my copy of the sample is current. I pulled just before running it.

**Comment by stevkan** [comment]
@slcwebguy, apologies for the long delay and thank you for your patience. I was able to locate where the problem is. The reason the sample's adaptive card is failing is due to the `url` property on line 44 (shown below) of the RestaurantCard.json file not being properly defined. As soon as a legitimate URL pointing to an image is supplied, the card then previews and is able to be submitted.

```js
"url": "<<YOUR-BASE-URL>>/Images/img1.jpg"

should be

"url": "https://somesite.com/images/some-image.jpg"
```

The same is true on line 8 of the ConnectorCard.json file:

```js
"activityImage": "<<YOUR-BASE-URL>>/Images/imgConnector.jpg"

should be

"activityImage": "https://somesite.com/images/some-image.jpg"
```

Lastly, is the code on line 99 of the teamsMessagingExtensionsSearchBot.js file. The `baseurl` variable is instantiated on line 12 with the value coming from the .env file. However, it looks like the .env file is missing the `BaseUrl=` property. What is more, if you add and define the property (and add an 'Image' folder and image file), the bot still won't be able to access the image as it doesn't appear to be configured for that. The easiest solution is to just supply a URL like in the JSON files by hard coding the value on line 99, like below.

**teamsMessagingExtensionsSearchBot.sj**
```js
[{ url: `$./public/Images/${file}` }]

should be

[{ url: `https://somesite.com/images/some-image.jpg` }]
```

Here is the adaptive card in action:

![messagingExtensionSearchImage](https://user-images.githubusercontent.com/18403946/165892959-a55966e0-e437-4196-b3f6-7724c16da51f.gif)

As this should resolve this issue, I am closing this. If the issue persists, please feel free to reopen this. However, any 'How to' type questions should be redirected to Stack Overflow for the greater community to answer.
