### ISSUE TITLE
Azure Bot skill - userTokenClient.GetUserTokenAsync - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ShilpaSharePoint** [microsoft/BotBuilder-Samples#3743]
Hi,

I am working on the sample 'skills-sso-cloudadapter' from the link: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/82.skills-sso-cloudadapter 
Below method in '**SsoSkillDialog**' class throws exception as Object reference not set to an instance of an object.
 **await userTokenClient.GetUserTokenAsync**

Does not get the token
[Error] Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Connection ID: An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.

I have followed all the instructions given in the readme file  & created resources on Azure.

**Comment by anishprasad01** [comment]
HI @ShilpaSharePoint,

There's probably something wrong with your configuration. As we are already discussing your difficulties with this sample on the [other issue](https://github.com/MicrosoftDocs/bot-docs/issues/2197) you opened, I'm going to close this in favor of that one, in order to keep things simple. There's a good chance both problems stem from the same cause.
