### ISSUE TITLE
Geolocation example

### ISSUE THREAD

**Issue by bandtank** [microsoft/BotBuilder-Samples#3757]
Geolocation is listed as a device permission option, but none of the examples explain how to use it. I also can’t find information in the documentation. Am I missing it? I don’t understand why the permission exists if it can’t be used, so I’m not sure what to do.

**Comment by bandtank** [comment]
What I intended was to highlight the permission to return the user's location in Teams:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/1170415/169648345-23998e58-771c-4668-96a5-bc467315c0d0.png">

I have not been able to find an example that uses location data. Does such a thing exist? I managed to locate [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability), but I don't understand how to use it.

**Comment by stevkan** [comment]
@bandtank, unfortunately, this doesn't appear to be related specifically to the BotBuilder-Samples repo. It also looks like you asked this [question](https://stackoverflow.com/questions/72319518/how-to-access-geolocation-information-in-a-teams-bot/72323352#72323352) in Stack Overflow and received a response from someone on the Teams team indicating it's not supported by BotFramework.

While their response is helpful (but not great, in my estimation), you could consider posting your question in the Docs Q&A forum and tag it with `office-teams-windows-itpro`. The forum is pretty active There may be other tags you could use, as well.

Because this is unrelated to the repo and is outside our area of knowledge, I am closing this.
