### ISSUE TITLE
bot response

### ISSUE THREAD

**Issue by Rbsn-joses** [microsoft/BotBuilder-Samples#3775]
Good afternoon, I would like to know if the outgoing webhook only receives one message at a time, I would like that as soon as the user mentioned the bot, the bot would send 2 or 3 different messages , but I tried here and it always happens "Sorry, there was a problem encountered with your request", only one answer works, I would like to know if it is even possible

ex: 
@bothello hello

the bot response:

bothello hello

bothello how are you?

**Comment by anishprasad01** [comment]
Hi @Rbsn-joses,

In order to assist you, we need a lot more information. As it stands, I have no idea what programming language you're using, what bot sample you're using, what your config looks like, what modifications you have made to the code, your Azure config (if applicable), or what webhook you are referring to.

If you could please provide these details along with a sample of the code that isn't working, I may be able to assist you.

Additionally, you may find the [bot framework documentation](https://docs.microsoft.com/en-us/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0) helpful for general knowledge on how to implement various bot features.

**Comment by Rbsn-joses** [comment]
basically I created a webhook outgoing and I created a bot in golang that when the user puts something mentioning the bot, this message is sent to him and he does a simple processing and then comes back to the message that I configure as a response.
It is a pure bot, using this link here
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet

the only difference that I created a webserver in golang that receives the request from teams

**Comment by anishprasad01** [comment]
This repository is only for issues concerning the Samples built for demonstrating the feature of the Microsoft Bot Framework SDK. In addition, we do not have a Golang Bot Builder package. 

Unfortunately, we cannot help you with your custom solution. If there are issues with Teams, please raise them with Teams support. This issue will be closed.
