### ISSUE TITLE
Typescript Samples not building

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotBuilder-Samples#3975]

**Comment by gandiddi** [comment]
Hi @tracyboehrer, The TypeScript samples are currently using an older version (_4.3.2_) of TypeScript, which is causing failures due to its outdated nature. I have already updated the TypeScript version to _4.9.3_ in the TSLint to ESLint migration [Pull Request #3969](https://github.com/microsoft/BotBuilder-Samples/pull/3969), and it is awaiting approval.

Could you please share the error details or screenshots if further investigation is needed? Thank you!.
