### ISSUE TITLE
[Docs] How-To/Develop/"Manage conversation and user state" covers too many concepts

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#902]
## Describe the bug
Docs/How-To/Develop/"Manage conversation and user state" covers too many concepts, misses goal, causing confusion

## Additional context
Link to docs:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp

Intro to state doc should cover a) bots are web api apps, so stateless, b) human conversation is stateful, c) BBV4 provides state api to make conversation modeling stateful.

[bug]

**Comment by Kaiqb** [comment]
The topic referenced in the bug is about [creating your own prompts and validating it](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp). It is not about [Managing User and Conversation State](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp) topic as mentioned in the issue title.
