### ISSUE TITLE
azure chatbot not working. after publishing from visual studio(2017)

### ISSUE THREAD

**Issue by sumithsudesan** [Microsoft/BotBuilder-Samples#932]
i done the following steps:

created web app bot (bot framework sdk v4) and perform 'test web chat'. which is successful and the bot responded. note: Microsoft app id and password are created.

Downloaded the code.

updated bot file(.bot) with luis and qna configuration manually

#{ "appId": "XXXXXXX", "authoringKey": "xxxxxxxxxx", "version": "0.1", "region": "xxxxx", "type": "luis", "name": "BasicBotLuisApplication", "id": "6"

}
{
"appId": "XXXXXXX", "authoringKey": "xxxxxxxxxx", "version": "0.1", "region": "xxxxx", "type": "qna", "name": "myqna"

}
and put 'Padlock' with empty value

Also updated the code (Startup.cs,BotServices.cs) and build app locally.

For testing locally,used bot framework emulator and which was successful.
Then 'Publish' the application with visual studio.
Try to connect with 'Test webchat'. The operation failed and received error code(401 and 403).
what shall do? any solutions?

**Comment by Diruuo** [comment]
The QnA service is defined in the following way within the .bot file: 

```
            {
            "type": "qna",
            "endpointKey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "hostname": "https://<your app service name here>.azurewebsites.net/qnamaker",
            "id": "xxx",
            "kbId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "name": "myqna",
            "subscriptionKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            }
```

Subscription key you get from the cognitive service resource in Azure (Cognitive service -> Keys), the endpoint key, the hostname and the kbID you get from the QnA portal after publishing your QnA model.

**Comment by vishwacsena** [comment]
@sumithsudesan - how did you update the .bot file? Did you use the MSBot CLI to first decrypt the bot file before adding the QnA and LUIS sections? Note that just removing the padlock does not decrypt the bot file. 

Also if you re-encrypted the bot file, then you need to update the botFileSecret application settings. 

Based on your flow, if you downloaded the source code, opened the bot file, removed the padlock and added the qna sections, you will be able to connect to your bot using the V3 emulator (but not V4) and the bot will fail when published to azure since it is trying to set an encrypted value for MSA appSecret which should be decrypted. 

To better assist you, please provide clarity on exact steps you followed as well as what version of CLI tools and or emulator you are using.

**Comment by sumithsudesan** [comment]
@vishwacsena - 
Did you use the MSBot CLI to first decrypt the bot file before adding the QnA and LUIS sections? 
No, i didn't use MSBot CLI.

Initially i was unaware that  bot file configurations should not be updated manually. 

That's why i removed 'padlock' from bot configuration and added qna configurations directly
{
"type": "qna",
"EndpointKey": "XXXXX",
"Hostname": "XXXXX",
"KbId": "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
"name": "QnABot"
}
Since the padlock is removed, 'EndpointKey' need not be encrypted. 
So i updated 'EndpointKey'  value with exact value provided in Qna application.

These are the steps i done , after downloading the source code

**Comment by sumithsudesan** [comment]
@vishwacsena 

Could u please help to solve following doubts:
1 . Does it really required to encrypt the file?

2. Can i use 'bot framework emulator' to encrypt bot file with new configurations?
    in such scenario,  is it necessary to update the new configurations details to any other places like settings in azure?

**Comment by vishwacsena** [comment]
@sumithsudesan - Thanks for clarifying. When you create a web app bot in the Azure portal, the .bot file is encrypted. you can find the key to decrypt the bot file under application settings with key name 'botFileSecret'. 

To correctly decrypt the bot file, you need to use the [MSBot](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/MSBot) CLI tool and use the following command - 
```bash
> msbot secret --clear --secret <YOUR-SECRET>
```

Alternately you can also use the [Bot Framework Emulator](https://github.com/microsoft/botframework-emulator) to open the .bot file, provide your key and leave the bot file un-encrypted via the settings gear. 

Few additional notes - 
1. Removing the padlock does not leave the bot file decrypted. You really need to decrypt the bot file either using the MSBot CLI or the Emulator for it to be correctly decrypted. 
2. You can add new services even when your bot file is encrypted. As an example, since you are trying to add a QnA Maker service, you can use the [QnA Maker CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/QnAMaker) and the MSBot CLI via this command and continue to keep your bot file encrypted. 
```bash
> qnamaker init
> qnamaker get kb --msbot --hostname <YOUR-HOST-NAME> --endpointKey <YOUR-ENDPOINT-KEY> --kbId <YOUR-KB-ID> --environment <TEST-OR-PROD> | msbot connect qna --secret <YOUR-SECRET>
```

This command gets your KB information as well as adds that service configuration to the .bot file while keeping your bot file encrypted. 

You can also use the Bot Framework emulator to [manage service configurations](https://github.com/Microsoft/BotFramework-Emulator/wiki/Managing-services) in your bot file. 

Finally, to answer your specific questions - 
- It is not required for the bot file to be encrypted but it is good practice since it contains the keys to all services your bot depends on. 
- When you change the bot file secret, you need to update your appsettings.json or .env or web.config file appropriately to reflect the new secret. This is only required if your bot is using the botframework-configuration library to read the contents of the bot file to manage service connections from within your bot's code. 
- Also, finally, when you change your bot file's encryption status or get a new encryption key generated, remember to update the key under application settings in azure portal for your bot. Without this setting, your bot code will attempt to read the bot file with an invalid key and the botframework-configuration library will fail or a subsequent service configuration will fail due to an invalid key. 

I'm marking this issue as closed as well as labeling this as support. Should you have additional questions here, you might want to engage via [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework)

**Comment by sumithsudesan** [comment]
@vishwacsena  thank u.
