### ISSUE TITLE
Displaying welcome message in Azure

### ISSUE THREAD

**Issue by hemachowdary** [Microsoft/BotBuilder-Samples#986]
Hi, 
I am currently working on sdk4  using nodejs for developing bots. In my bot I wanted to display a welcome message to the user before the user sends any message to the bot. I am able to get this as expected when I run the bot in emulator. I ran the code in Azure using "test in webchat", bot is not displaying the welcome message if it doesnt receive any message from the user. I tried running the "welcome-users" sample also given in github [here](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/03.welcome-users) sample is also working only in emulator. Is there any change that has made in sdk4 ?

**Comment by v-kydela** [comment]
You ask if this because of a change in V4. Do you mean to say you've experienced this differently when making bots in V3?

I understand the real reason behind this has to do with how conversationUpdate events work. Those events are handled differently in different channels, and some channels don't use them at all. Web Chat won't send conversationUpdate events until the user sends a message, so to make welcome messages work in Web Chat you may need to provide your own custom events. You can read more about that here: https://blog.botframework.com/2018/07/12/how-to-properly-send-a-greeting-message-and-common-issues-from-customers/

**Comment by hemachowdary** [comment]
thank you kydela
